### ISSUE TITLE
books:admin_pencil ne marche plus

### ISSUE THREAD

**Issue by mgl512** [MT-Eurythmia/Eurythmia-server#111]
Je pensais que c'était un lag mais ça ne marche pas non plus sur un Eurythmia singleplayer. Sur un monde mt_game + mod books, il marche.

Le clic droit avec l'admin pencil en main ne fait rien du tout sur un livre. Sur un livre fermé, il devrait l'ouvir mais, même ça, ça ne marche pas. Et un clic droit sur un livre ouvert avec l'admin pencil en main ne montre ni la formspec éditée, ni la formspec originale. Ça ne fait rien du tout. Je m'en suis servi quelques jours après l'installation des divers batons (sending, boom etc). Ça marchait encore sur le serveur à ce moment-là.

**Comment by paly2** [comment]
J'ai tenté d'effectuer une correction, je ne sais pas si elle fonctionne. À voir demain, après le reboot

**Comment by paly2** [comment]
L'admin pencil fonctionne à présent, après ce down d'une journée.
