### ISSUE TITLE
Serveur, SSH down

### ISSUE THREAD

**Issue by mgl512** [MT-Eurythmia/Eurythmia-server#115]
Tout est hors ligne depuis le 18 juillet.

**Comment by mgl512** [comment]
Revenu le lendemain.

**Comment by mgl512** [comment]
Et de nouveau hors ligne le surlendemain.

**Comment by paly2** [comment]
Je ne sais pas précisément ce qui s'est passé. J'ai reçu de nombreuses alertes critiques (que je viens de pouvoir lire en obtenant à nouveau un accès à Internet). Le serveur a l'air en ligne à nouveau. Je reviens demain.

**Comment by fwhcat** [comment]
Le serveur SSH étant revenu avant ton retour, c'était forcément une perte de connexion réseau de ta box.
Je clôture ce ticket
