### ISSUE TITLE
Grief de lave

### ISSUE THREAD

**Issue by mega-gigaMynetest** [MT-Eurythmia/Eurythmia-server#118]
Un joueur (Ellens) a inonde le village de itchigo avec de la stone en metant une colonne de lave et une colonne d'eau à côté. J'ai mit 3 heures hier soir pour réparer 1/20 du grief total, qui a été remit des le lendemain matin...Vu le temps que ça nous a prit avec Docteur et matthieu et les lags que ça a cosé, il a été banni à vie. Nous estimons que c'est le deuxieme plus gros grief du serveur, une montagne de stone jusqu'a la couche 60 !
J'invite donc aux joueurs construisant des villes et des grandes maisons de faire des areas très hautes, pour minimiser ce genre de problème.
Cordialement
mega-giga

**Comment by paly2** [comment]
Duplicate. Voir #117

**Comment by mgl512** [comment]
Au sujet de griefs de ce genre, /rollback_check et /rollback sont devenues des commandes inutiles tellement elles prennent de temps et font laguer. /rollback_check prenait quelques secondes aux débuts du serveur. Il semble que la requête de la commande prend en compte tous les blocs révélés de la map parce qu'il n'existe aucun index de tri chronologique sur les blocs. Je me demande si c'est possible d'ajouter un index de tri chronologique à la main et de le maintenir régulièrement. Probablement pas. Je n'ai jamais lu le code sur les bases de donnée des blocs de la map. 

Je n'ai rien trouvé dans les logs qui explique le grief par Ellens. Elle a écrit vraiment très peu en anglais, un peu plus en cyrillique et a utilisé les commandes babel pour traduire son texte mais elle n'a vraiment pas dit grand chose. On la surveillait depuis qu'elle venait sur le serveur: champ et forets publics pas replantés. Elle s'était améliorée là-dessus. Elle a tenté de TP kill des joueurs aussi, dont matthieu. Elle en a eu quelques uns. Mais elle avait des alliés aussi.
