### ISSUE TITLE
Pb de collision box 0.4.16-dev

### ISSUE THREAD

**Issue by mgl512** [MT-Eurythmia/Eurythmia-server#120]
La 0.4.16-dev ravage la collision box des joueurs et NPCs. Avec mon client récent, je me vois flotter un bloc au dessus du sol, sans son sur les blocs sur lesquels je marche. Je peux passer les portes mais je me prends un bloc d'obscurité en les traversant. J'ai du mal avec les arbres dont les feuilles sont à 2 blocs du sol. Je vois les NPCs flotter pareil avec leur collision box normale. Mais la perception peut être inversée selon les clients: certains joueurs rapportent que ce sont les collision box des NPCs et des joueurs qui sont enterrées et leurs textures normales. Tous les joueurs que moi j'ai vus m'apparaissent normaux. 

La 0.4.16-dev a un commit qui annonce l'incompatibilité des nouvelles collision box avec les anciens clients. 

EDIT: Quand je me tp au spawn, je tombe à travers le sol...

**Comment by paly2** [comment]
Que se passe-t-il dans le cas d'un serveur récent avec un ancien client ?

**Comment by mgl512** [comment]
Je ne sais pas. Je n''ai que survoler des rapports de bugs et pull requests en suivant les traces de ce commit Minetest. Je n'ai vu que des histoires de joueurs qui flottent ou qui sont enterrés dans le sol. Il est question de porter le protocole minimum à 35 ou 36 je crois, donc d'interdire les anciens clients avec un serveur récent. C'est un problème d'incompatibilité de la future 0.5 avec les versions plus anciennes de Minetest. Le peu que j'ai lu suggère qu'on ne devrait même pas utiliser la branche master comme source pour compiler Minetest. Ils devraient commencer par cesser de l'appeler "0.4.16-dev" si elle est incompatible avec la 0.4 !

Sur Eurythmis, les joueurs aux clients anciens (je ne sais pas à quel point anciens) voient des problèmes de décalage de collision box sur les NPCs et les joueurs aux clients récents. Pour eux les textures des NPCs sont normales et leur collision box enterrée, pour moi leur collision box est normale par rapport au sol mais la texture des NPCs flotte un bloc au dessus de la surface. Le serveur est probablement déjà trop à jour pour ne causer de problème à personne. C'est pareil sur Axinite.

**Comment by paly2** [comment]
Si un serveur en 0.4.16-dev est incompatible avec les clients 0.4.16-stable, on ne peut pas se permettre de le mettre à jour avant 0.4.17-stable (qui s'appelera peut-être 0.5.0-stable). La dernière version stable doit rester une version que nous supportons officiellement.

**Comment by mgl512** [comment]
Le serveur comme il est est incompatible avec un client 0.4.16 stable, les NPCs ont l'air buggés.

Le passage en créatif par mod sans avoir l'écran saturé de messages de privs est incompatible avec un client 0.4.16 stable.

Et il y a une double tour de 1x1 de 150 de haut juste devant la porte du chateau avec grief de terre devant l'allée pour faire une maison flottante avec jardin pour lesquels je mettrais un ban de plusieurs mois à MeliGames / Caramella si je devais m'en occuper. Elle grief le paysage autour de la maison d'un autre pour faire la sienne en plus.

**Comment by paly2** [comment]
> les NPCs ont l'air buggés.

Ah oui. Bizarre. Je regarde ce qui a été changé  pour que ça devienne comme ça. Ni mon client ni le serveur n'ont été mis à jour, donc je suppose que c'est mobs

> Le passage en créatif par mod sans avoir l'écran saturé de messages de privs est incompatible avec un client 0.4.16 stable.

? Rien de tel n'est officiellement supporté par le serveur. Le serveur n'est pas en mode créatif, et propose un privilège `creative` qui simule quelques unes de ses fonctionnalités. Rien pour désactiver ce priv.

**Comment by mgl512** [comment]
> Rien de tel n'est officiellement supporté par le serveur
La commande qui me permet de me donner et enlever le priv créatif sans que mon écran soit saturé de texte.

**Comment by paly2** [comment]
J'ai testé de me connecter avec un client 0.4.16-stable et 0.4.16-dev sur un serveur 0.4.16-dev. Ça a fonctionné, mais le client 0.4.16-dev ne voit pas mieux les NPCs que le client 0.4.16-stable.

Bref, même si ça ne fonctionne pas encore bien, on peut mettre à jour 😃

**Comment by mgl512** [comment]
Tu ne flottes pas au dessus du sol avec un client 0.4.16-dev sur ton serveur ? Avec aucun bruit des blocs au sol.

**Comment by paly2** [comment]
> Tu ne flottes pas au dessus du sol avec un client 0.4.16-dev sur ton serveur ? Avec aucun bruit des blocs au sol.

Non je n'ai pas eu l'impression. Mais de toute façon, à partir du prochain reboot, le serveur sera à la dernière version 0.4.16-dev. On verra les problèmes que ça pose

**Comment by mgl512** [comment]
Le thread sur l'avertissement aux serveurs 0.4.16-dev / master qui deviennent incompatibles avec les anciens clients officilels: [Minetest 0.5 is on the road](https://forum.minetest.net/viewtopic.php?f=18&t=17929)

**Comment by paly2** [comment]
Intéressant. Selon ce thread, nous devrions donc revenir en 0.4.16-stable. Je laisse quand-même en 0.4.16-dev pour voir ce que ça donne demain, et ensuite je recompilerai sans-doute sur la branche 0.4-stable.

Note: maintenant que nous utilisons un fork de minetest, nous pouvons facilement backporter les fonctionnalités qui n'existaient pas encore lors de la sortie de 0.4.16-stable, telles que ce réglage `strip_color_codes` que j'hésite à activer.

**Comment by mgl512** [comment]
Sur le serveur 0.4.16-dev, avec mon client 0.4.16-dev ou 0.4.16 stable, je vois les NPC flotter et tous les joueurs enterrés. Mais je ne flotte plus moi-même. Le jeu se passe normalement pour moi. Tout le monde me voit enterré et il semble qu'ils se voient enterrés entre eux aussi. Il n'y a pas un seul joueur que je n'ai pas vu enterré et tous m'ont vu enterré aussi. Il n'y a que les animaux et les monstres qui sont normaux. 

fwhcat et moi en client 0.4.16 stables sur serveur 0.4.16-dev, nous nous voyons enterrés. Donc _le serveur n'est même pas compatible avec le client officiel le plus récent_.

**Comment by mgl512** [comment]
MT_Game devrait être gelé aussi à cause de ce commit: [Player model: Remove vertical 1 node offset](https://github.com/minetest/minetest_game/commit/886537ef50a6def0927676f1e1a7932c506fd6a6)

```
Player model: Remove vertical 1 node offset
Required due to the settable player collision box engine feature.
Change for MT/MTG v0.5.0 that breaks compatibility with old clients.
```
Comme le dépôt minetest, le dépôt minetest_game a une branche stable-0.4. Ne plus mettre  à jour sur Eurythmia devrait suffire. MT_Game a des recettes d'escaliers en coin redondants avec ceux de l'établi de xdecor peut-être. Avec un peu de chance, ils ont les mêmes noms et on s'en fiche.

**Comment by matt8fr** [comment]
Donc ont joue en 0.4.16 stable ?

**Comment by mgl512** [comment]
Le serveur est en 0.4.16 stable. Si ton client est en 0.4.16-dev, tu vas voir les joueurs enterrés et toi-même tu flotteras un bloc au dessus de la surface sans son de marche. Les autres te verrons flotter aussi. La 0.4.16-dev est incompatible avec la 0.4.16, c'est pour ça qu'elles ont le même numéro de version. Faut pas chercher à comprendre, c'est les devs Minetest...

**Comment by mega-gigaMynetest** [comment]
Mdt

**Comment by mega-gigaMynetest** [comment]
Mdr*
