### ISSUE TITLE
Les monstres spawnent en masse dans les areas

### ISSUE THREAD

**Issue by mgl512** [MT-Eurythmia/Eurythmia-server#121]
Ce ne sont pas des areas ouvertes pourtant. J'ai croisé 4 sandmonsters et une araignée à la gare de Stonebury par exemple. Il y en a à la ferme du spawn aussi, mais le champ est ouvert. Le champ n'a pas de bloc ou un dirtmonster peut spanwer cependant. Or on en trouve. 

Le code de mobs faisait un appel minetest.is_protected() sur le bloc de spawn la dernière fois que je l'ai lu. EDIT la prise en compte des coordonnées des areas arriverait après le code de vérification de protection de mobs ?

**Comment by matt8fr** [comment]
il y avait une area open sur la place de Stonebury, mais elle n'est plus la ! bizarre ces mobs !

**Comment by matt8fr** [comment]
c'est depuis le spawn des igors que les mobs pop partout.

**Comment by paly2** [comment]
C'était un nouveau réglage de mobs que je n'avais pas vu arriver :-) (`mobs_spawn_protected` dont la valeur par défaut est `true`). Je corrige ça :p

**Comment by mgl512** [comment]
Pour moi, de ce que j'ai lu du code de mobs quand l'API faisait la moitié de sa taille actuelle, ce paramètre "mobs_spawn_protected" signifie juste que les mobs non hostiles peuvent spawner dans les areas, il ne concerne pas les monstres. Le mettre à faux empêchera tout spawn de mob dans les areas. Les mobs hostiles ne sont gérés que par un appel minetest.is_protected() sur le bloc sur lequel on veut les faire spawner.

**Comment by paly2** [comment]
Ah, mince, c'est exact. Il semble que le mod ne fasse plus de différence entre les mobs agressifs et les mobs passifs pour le spawn dans les areas. Les deux sont contrôlés par cet unique paramètre `mobs_spawn_protected`.

**Comment by fwhcat** [comment]
Est-on sûr de vouloir désactiver tous les mobs ? Les animaux qui spawnent dans une area ne me gènerait pas, au contraire... En tout cas, j'ai demandé en upstream de distinguer les monstres des animaux pacifiques: https://github.com/tenplus1/mobs_redo/issues/108
