### ISSUE TITLE
Revenge grief de ce fumier de tyty_28

### ISSUE THREAD

**Issue by mgl512** [MT-Eurythmia/Eurythmia-server#122]
Personne s'est occupé de son cas à ma place, il est venu faire du grief colossal lave+eau au spawn

le_vrait_tyty28 est ban.

rollback 24h de le_vrai_tyty28 et Un_seche_cheveux, il a utilisé ses 2 comptes. Rollback de Un_seche_cheveux INTERMINABLE, le bot Eurythmi s'est fait déco rapidement. 
EDIT: le compte le_vrai_tyty28 n'a pas utilisé de seau, pas besoin de le rollback. 

Il va surement falloir restaurer une sauvegarde de la carte. Il a fait son grief vers 22h et 2h du matin, c'est foutu pour la sauvegarde nightly je pense.

Un truc que je fais parfois: définir une zone WE et remplacer la stone par du papyrus. On casse le papyrus en surface à plusieurs (le bloc du pied casse toute la colonne) et on retransforme ce qu'il reste sous terre en stone après.

Le Rollback a pas tout rollbacké mais c'est acceptable maintenant. Je fais le truc du papyrus sur le reste. EDIT: Grief réparé, papyrus volant probable.

**Comment by mgl512** [comment]
Il faut une vraie sauvegarde quotidienne, pas qui qui est faite à 4h du matin juste après que les griefers nocturnes soient passés.

**Comment by paly2** [comment]
Ok merci. Effectivement je n'ai pas ban le_vrai_tyty28 hier, je comptais le faire aujourd'hui.

La sauvegarde de la map prend plusieurs minutes à s'effectuer. Comme laisser le serveur tourner (et donc la map se faire modifier) pendant la sauvegarde est potentiellement une source de sauvegarde corrompue, il est nécessaire de l'éteindre, ce qui n'est vraiment pas agréable pour les joueurs quand cela s'effectue en pleine journée.

Une autre solution que je propose est de conserver la sauvegarde nightly de deux jours consécutifs, afin d'éviter de devoir immédiatement se rapporter à la weekly si la dernière nightly n'est plus utilisable.

**Comment by mgl512** [comment]
> Une autre solution que je propose est de conserver la sauvegarde nightly de deux jours consécutifs, afin d'éviter de devoir immédiatement se rapporter à la weekly si la dernière nightly n'est plus utilisable.

C'est ce à quoi je pensais. Parce qu'on n'a pas réellement de sauvergarde de la veille, on a une sauvegarde, faite en aveugle, qui efface celle de la veille. Faudrait même en avoir des 2 jours précédents, il y a bien plus de chances qu'on ait besoin de l'une de celles-là que de la weekly ou monthly. 

Un script pour remettre une sauvegarde en service serait bien aussi. Là j'ai du regarder, avec fwhcat,  dans le script de backup où se trouvait le backup et si je pouvais le remettre en circulation. Et puis j'ai réalisé que le backup avait sauvegardé le grief. Même pas sûr que j'aurais pu le remettre en service. 

fwhcat a une nouvelle clé publique à mettre ne service, il n'a plus d'accès SSH.

Sur Axinite, Sporax n'a pris aucune mesure contre tyty pour le racket des joueurs (il n'a même pas lu ses logs je pense, il prétend qu'il était là alors que tyty28 était le seul modo présent) et n'en prendra probablement pas non plus pour le grief sur Eurythmia par l'un de ses modos au priv ban. Peppy, son adjoint, a quitté Mynetest pour Axinite à cause de Lord_discodlm57 pour beaucoup moins que ça. Cet incident va causer des remous sur les joueurs pendant un certain temps je pense. Il y a quand même un grief majeur (le 3ème de l'histoire du serveur) d'un cadre d'Axinite sur Eurythmia. Moi-même je ne retournerai pas jouer sur Axinite.

**Comment by mega-gigaMynetest** [comment]
Je suis assez d'accord avec tout ce cas dit mlg, je voulais aussi faire une avant ure axinite à la rentree avec mon ordinateur, mais je n'en ai plus du tout envie, mon idée pour éviter ces griefs est d'empecher la pose de lave si on est au dessus de la couche 0.

**Comment by mgl512** [comment]
Pour l'histoire: grief de lave de Berwix au spawn, autre membre de la team du modo maléfique. 

Bonne idée le seau de lave pas au dessus de la surface. Il doit même y avoir un paramètre quelque part qui indique le niveau de l'eau maintenant, plutôt que juste "0".

**Comment by paly2** [comment]
Pour ce qui est du seau de lave dont la pose est interdite dans les y positifs (ce qui ferait beaucoup râler les joueurs), Sporax propose une autre solution moins radicale: que l'eau au contact de la lave ne crée pas de la `default:stone`, mais un autre node parfaitement identique mais portant un nom différent (et donnant de la vraie `default:stone` lorsqu'il est cassé) afin de pouvoir être facilement enlevé au WorldEdit sans enlever toute la vraie pierre.

**Comment by mega-gigaMynetest** [comment]
Tu peux faire ça aussi paly2, mais les lags de We seront toujours présents

**Comment by mega-gigaMynetest** [comment]
@mlg512 peux tu me décrire l'étendue des dégâts du grief de Berwix ?

**Comment by mgl512** [comment]
> @mlg512 peux tu me décrire l'étendue des dégâts du grief de Berwix ?

Ber the Weak a totalement raté son attaque contre Eurythmia par les membres du staff d'Axinite protégés par Sporax: Il a posé un seau de lave dans le champ public et a oublié d'ajouter de l'eau à sa lave qui était contenue par les légumes et les barrières. C'était la plus minable attaque à la lave que j'ai jamais vue mais l'intention de nuire y était. Quand je suis allé sur leur IRC, ubyzoo et le reste de leur team célébraient leur victoire et Sporax était totalement silencieux. 

A 0-0, Upsilon, fwhcat et moi nous aurions supprimé ses privs à tout modo qui aurait attaqué un autre serveur. Et nous l'aurions probablement banni, nous n'aurions pas cherché à le justifier. Là on est à 0-2 et Sporax nous soumet des idées pour nous défendre contre les attaques de son staff ? FC UK

**Comment by mgl512** [comment]
> @mlg512 peux tu me décrire l'étendue des dégâts du grief de Berwix ?

Ber the Weak a totalement raté son attaque contre Eurythmia par les membres du staff d'Axinite protégés par Sporax: Il a posé 9 seaux de lave dans le champ public et a oublié d'ajouter de l'eau à sa lave qui était contenue par les légumes et les barrières. C'était la plus minable attaque à la lave que j'ai jamais vue, surtout pour échouer avec autant de seaux. Mais l'intention de nuire y était. Quand je suis allé sur leur IRC, ubyzoo et le reste de leur team célébraient leur victoire et Sporax était totalement silencieux. 

A 0-0, Upsilon, fwhcat et moi nous aurions supprimé ses privs à tout modo qui aurait attaqué un autre serveur. En particulier un serveur avec lequel on a des liens. Et nous l'aurions probablement banni, nous n'aurions pas cherché à le justifier. Là on est à 0-2 et Sporax nous soumet des idées pour nous défendre contre les attaques de son staff ? FC UK

**Comment by matt8fr** [comment]
C’était le coin de plage ou j'ai aidé ?

**Comment by mgl512** [comment]
> C’était le coin de plage ou j'ai aidé ?

Non, un grief plus récent de tyty28, modérateur avec ban sur Axinite et Minetest France. Deux zones du spawn ont été attaquées à la lave + eau : la ferme à cactus et la zone où se trouve la forêt publique, entre la tour commerciale et la maison au mur en cire d'abeille au nord-ouest de la tour. Il doit rester du papyrus volant dans la zone, qui était de la pierre avant. Le champ public attaqué à la lave le lendemain.

**Comment by mega-gigaMynetest** [comment]
Petit résumé actuelle de la situation, la moitié d'Axinite veut mettre le bazarre chez nous, je me fait traité de tous les noms dans mon dos par Agent et sa team et Sporax ne dit absolument rien. Cependant pour l'instant je n'ai remarque aucun gros grief pendant l'absence de Upsilon et Le_Docteur

**Comment by paly2** [comment]
> la moitié d'Axinite

Loin de là, seulement une bande de quatre joueurs tout au plus qui prennent du plaisir à se monter la tête. Je ferme cette issue.
