### ISSUE TITLE
Knockback

### ISSUE THREAD

**Issue by mega-gigaMynetest** [MT-Eurythmia/Eurythmia-server#123]
Plusieurs joueurs ( et moi ) ce sont demander si il était possible de rajouter un knockback ( un recul quand quelque chose tape ) à minetest. Je sais que c'est très probablement impossible ou très compliqué, et que cette issue sera rapidement fermée, mais bon, qui ne tente rien n'à rien.

**Comment by matt8fr** [comment]
cette fonction est en [dev ](https://github.com/minetest/minetest/pull/5679)

**Comment by paly2** [comment]
Pas encore en dev, non... C'est une PR qui n'est pas encore mergée. Je ferme en effet cette issue ; car la discussion se trouve plutôt sur la PR référencée par @matt8fr :-)
