### ISSUE TITLE
Reset et passage en V7

### ISSUE THREAD

**Issue by mega-gigaMynetest** [MT-Eurythmia/Eurythmia-server#125]
Aujourd'hui, le serveur a plusieurs problème, il a quelques problèmes: le grief, le trop de stuff et la V6. J'avais déjà proposer ca a Upsilon lors du changement de nom, mais il n'était pas tres d'accord. Alors je propose un vote ou l'on reset la map, le stuff et où on passe en V6. Si plus de 60% disent oui, il aurait lieu.
Le gros problème...Ce serait les builds, tant de builds perdus...Mais certains pourraient êtres sauvegardees, mais ça demanderait des heures de terraforming  ( on pourrait changer le spawn aussi ) si je propose cette issue c'est qu'il y a deja un vote "oui" de ma part.
mega-gigaMynetest

**Comment by matt8fr** [comment]
Je suis pour un reset, a l'heur actuel 80% de la zone du spawn est occuper par des build de joueurs disparue,
après oui que faire de nos builds ! le mieux aurait était une double map comme sur minecraft mais ce n'est pas encore faisable!

**Comment by fwhcat** [comment]
Salut, perso ça m'est égal un reset, mes constructions sont moches. Mais je suis pour sauvegarder tout ce qui est joli, quitte à ce que plusieurs décident que sauvegarder ou pas. Les constructions de @matt8fr sont superbes et mériteraient un serveur à part entière lol

**Comment by fwhcat** [comment]
![screenshot_20170815_115119](https://user-images.githubusercontent.com/20411249/29427643-bc3c41e2-838a-11e7-9924-ff18d46755bc.png)
![screenshot_20170815_115200](https://user-images.githubusercontent.com/20411249/29427642-bc3ba21e-838a-11e7-8d8f-0824304ece17.png)

Voici de récentes constructions d'AJM.

Il y a aussi les machines de Getsuga, la ferme de mega-giga, les maisons d'eMuRe, etc.

A mon humble avis, il faut juste virer les vielles constructions abandonnées et proches du spawn et libérer la place pour de vrais builders.

**Comment by mega-gigaMynetest** [comment]
Il y a énormément de choses que l'on ne peut pas détruire, mais un autre problème est qu'il y a trop de stuff pas legit, et que la map est pas en V7.
La V7 c'est pas super grave, il y a juste plus de relief, mais aujourd'hui y'a plus le côté survie du serveur, appart au spawn tout le monde a un full diamand et full mitrille...Et bcp trop de nyan.

**Comment by fwhcat** [comment]
Idée pour la migration:
- mettre un serveur avec map en v7 sur un autre port (ne pas le lister publiquement)
- définir les zones à exporter via worldedit
- trouver les bons endroits dans la nouvelle map pour les importer et sauvegarder les coordonnées également
- a la migration réelle nous n'aurions plus qu'à avoir un script qui refasse les exports des areas définies (au cas ou elles ont changées), puis les importe en masse aux coordonnées spécifiées dans la nouvelle map

**Comment by mega-gigaMynetest** [comment]
Tu veux faire une map fermée avant de l'ouvrir au public ? Superbe idée, j'aiderais a trouver les endroits, et on refera un spawn, ça donnera du frais au serveur. Et pourquoi pas mettre quelques autres mods donnant encore plus l'effet de survie

**Comment by mega-gigaMynetest** [comment]
J'ai discuté avec JAPP ( qui est pour le reset ) de ce qu'il y a changer au niveau du pvp :
-ajout du knockback, désactivé lors du pvp désactivé
-Augmentation des dégâts des épée et diminution de la résistance des armures mitrille et diamant
-Faire des évents pvp réguliers.

Autres idées :
On pourrait rendre le pve un peut plus difficile, en augmentant les points de vie et légèrement les dégâts des montres.

Je pense que l'ajout d'un mod comme technic mais en beaucoup moins lourd pourrait donner d'y frais au serveur.

Privilégier les builds avec un priv donnant le creatif qu'aux block de construction  ( bloc de minerai exclus ) et pas de stuff, pouvant etre donner pour un proget.

Augmenter la rareté du diamant et diminuer celle du nyan

Changer le block fait par le mélange eau/lave (#122)

**Comment by paly2** [comment]
Je trouve de nombreuses idées proposées par cette issue très bonnes.
Il faudrait en effet diminuer la résistance des armures les plus fortes. Éventuellement augmenter la force des épées, qui s'accompagnerait d'une augmentation équivalente de la résistance des monstres.
Je ne suis pas pour augmenter la difficulté du Pve, le serveur ayant été prévu dès le départ pour être facile.
Je trouve la rareté des minerais pas trop mal choisie actuellement, pourquoi la changer ?
Pour technic, il n'existe rien de similaire en moins lourd ; et très peu de joueurs seraient capables de l'utiliser de toute façon. Je pense que Mesecons, MoreMesecons, Hoppers et notre petit pipeworks_like suffisent.
Le priv creative limité est une excellente idée.

Pour le choix du générateur, v7 n'est pas la seule solution à considérer. Il y a aussi valleys et le tout nouveau Carpathian que j'ai peu testé mais qui pourrait être très intéressant. 

Note: je re-rentre de vacances demain.

**Comment by mega-gigaMynetest** [comment]
Du coup tu serais pour ou contre reset ?

**Comment by paly2** [comment]
Si les joueurs sont d'accord, pourquoi pas. Mais il faudra établir une liste très précise des zones à transférer. Il faudrait aussi que l'ancienne map reste téléchargeable par les joueurs, ce qui implique de la convertir depuis son format actuel MTDB en SQLite -- à ma connaissance, rien n'existe pour le faire dans ce sens actuellement.

S'il vous vient à l'esprit des idées de changements qui ne peuvent se faire que par l'intermédiaire d'un reset (exemple: mapgen moretrees), c'est le moment de les soumettre !

**Comment by mgl512** [comment]
Vous êtes sûrs que la v7 est stable ? J'ai vu passer un post des devs sur le forum en 2017 qui annonçait l'incompatibilité de la v7 avec elle-même. Les serveurs qui utilisaient l'ancienne v7 de l'époque ont dû soit faire un reset forcé, soit ne pas faire de mise à jour de minetest.

La v7 est, pour moi, la plus moche des mapgen. La v5 avait un aspect de monde fantastique, la v7 se veut réalise (= copie intégrale de Minecraft) mais elle a un aspect fantastique horrible : donjons dans le ciel, montagnes avec des excroissances au sommet en pyramide inversée (les "montagnes tordues"), ilôts flottants partout, érosion inversée (en pyramide inversée). Il y a des paramères (minetest.conf) pour empêcher les montagnes tordues et les donjons dans le ciel mais les autres horreurs de mapgen restent. Les arbres de la mapgen v7 sont des arbres antiécologiques qui griefent le paysage avec leur tronc dans le sol. Ils ont un aspect moche en plus. Pour progresser dans un monde v7, il faut grief : les montagnes se franchissent par des tours de 1x1 et les plateaux en érosion inversée par des ponts de 1x1. Le grief de paysage devient insanctionnable parce que c'est forcé par la mapgen. Valleys me semble plus beau et plus stable mais c'est encore plus hostile à la construction que la v7. La v6 reste ce qu'il y a de plus rapide à générer pour le serveur. Je n'ai jamais testé Carpathian, découragé par sa présentation dans le commit ou dans sa doc mais je ne sais plus pourquoi. 

Je n'apprécie pas les reset serveur. Le spawn sera toujours grief, les joueurs construiront toujours leurs mochetés le plus près possible du centre. J'en ai détruit des dizaines et refait le paysage mais il y a toujours un nouveau joueur qui revient faire une construction-grief à la même place et qui disparait du serveur. Pour le stuff, je me souviens avoir mis un panneau de reprise de construction grief à thyo pendant un mois + mail. Il jouait encore, avait 14 têtes de nyan dans un coffre qu'il n'a jamais jugé bon de récupérer avant que je détruise sa maison... 

S'il y a reset, je ne vois pas pourquoi garder moreore(s). L'argent ne sert à rien et le mithril était fait, dans l'esprit, pour être plus rapide, plus durable et plus nul que le diamant. Les outils du mod moreores avaient un maxlevel de 1 (pioche en pierre) il y a quelques mois. La pioche ne cassait pas l'obsidienne. Maintenant c'est 2, elle ne casse pas les blocs de diamant. Ils se sont juste trompés sur l'épée, qui est la meilleure de toutes. Ce sont les mods qui utilisent moreores qui font du mithril un matériau exceptionnel, comme fishing ou 3d_armor. 

Je ne suis pas non plus pour la modification des épées, armures et mobs. Ça a été un fiasco complet sur MFF avec des bébés lapins qui one-shot et les épées et armures cassées au bout de 4 mobs. Ce ne sont pas les contraintes du jeu qui font la survie mais les contraintes qu'on s'impose à soi-même. Si tout est facile avec le meilleur stuff, si les gens qui jouent sur tél sont trop nuls au PvP, ne portez pas d'armure tout simplement. Si les minerais sont trop abondants pour ceux qui passent des heures à miner, imposez-vous de ne miner que ce qui est apparent dans les grottes, de ne jamais creuser au hasard dans l'espoir de trouver des minerais. Mais n'imposez pas à ceux qui veulent construire de galérer pour trouver de quoi se faire des outils.

**Comment by matt8fr** [comment]
Je suis pour une mapgen plus plate je vous laisse voire la quel je ne m'y connait pas.
c'est surtout un mod plus complet que xdécor qu'il nous faudrait, home décor est par contre trop lourd, existe t'il une alternative ?
moretree c'est une bonne idée, j'ai également pu tester clay crafter qui est cool.

Pour les armures je comprend @mgl512  mais la les mobs ne font vraiment aucun dégâts si on a une armure...

Pour les minerais je suis d'accord avec @mgl512: la on est bien.

Pour les grief/boite a chaussures de kikoos qui parte vite il nous faudrait une zone tampon. ( après avoir tapé le code on est tp dans une ville fermer pour faire nos preuve/faire une quête ...) après cela on a accès au reste de la map.

**Comment by mgl512** [comment]
> Pour les armures je comprend @mgl512 mais la les mobs ne font vraiment aucun dégâts si on a une armure...

Il suffit de ne pas en porter... Ça n'a pas de sens de se plaindre qu'on est trop fort avec du stuff. Modifier mobs + armures + épées = fork + maintenance de MT_Game, mobs et 3d_armor. On peut peut-être le faire sans fork pour MT_Game et les armures mais la maintenance reste. Sur MFF, le "fine tuning" du stuff a donné un serveur avec plus de développeurs que de joueurs et, je crois, le besoin de 24 ou 32 lingots de mithril rien que pour faire les chaussures d'une armure qui protège jusqu'à ce qu'elle casse. Je suis pour supprimer 3d_armor dans ce cas-là.

**Comment by paly2** [comment]
Ce qui est arrivé à MFF après les modifications des armes/armures/mobs me dissuadent en effet assez d'essayer de faire la même chose ici.

Et il est vrai que v7 n'est pas sans défauts. v6 a l'avantage d'être très adapté au build, avec peu de reliefs (notons cependant que v6 est très paramétrable, hauteur des reliefs comprise, mais on aura toujours un paysage généré avec du bruit de Perlin 2D). Valleys, au contraire, génère des montagnes très hautes et des rivières, ce qui rend très difficile de correctement intégrer les builds au paysage. v7 a un peu les mêmes symptômes.

Caparthian, quoique très en développement, est selon moi la meilleure option. Il génère de grandes plaines dont les reliefs dépassent rarement 5 nodes au dessus du niveau de la mer, des forêts de différents types (pommiers-trembles, pins, jungles, etc), et d'immenses chaînes de montagnes tout à fait fantastiques dont la hauteur dépasse facilement des 200 nodes (avec des rivières dans les vallées et des cascades géantes). Il génère bien sûr aussi des déserts, des plaines d'herbe sèche et des montagnes et plaines glacées.
Carpathian sera disponible dans 0.5.0 stable.

**Comment by matt8fr** [comment]
Avec vos argument je valide l'idée de ne rien toucher aux armures.
Caparthian semble interessant, on pourra faire des test avant de lancer le reset.

**Comment by matt8fr** [comment]
Peux-êtres manque t'il aussi un objectif/but/... après avoir miner quelque minerais, avoir construit une maison, que reste t'il a faire en jeux ?

Je sais Upsilon que tu voulait créer un serveur simple en jeux mais la ont est trop simple.
quelque exemple: les travelnet ne sont pas assez cher, résultat des réseaux dans tout les sens, et les ascenseur ne sont donc pas ou peux utilisé.
l’ajout d'un truc cool genre beacon/armure de couleur/super-pouvoir ...  super cher (25 mithril + 10 block de diamand ....)
développer un-peux plus les tournois ( grande arène près du spawn, un bouton pour lancer un tournois...)
+d'autre mini-jeux (soccer ...)

d'autre idées ?

**Comment by mega-gigaMynetest** [comment]
Bon, vu tout ce que j'ai à dire, je vais faire dans l'ordre pour pas me perdre.

En ce qui concerne la V7, je comprends que ce n'est pas une bonne idée, et Caparthian a l'air d'être une bonne idée.

En ce qui concerne les alentours du spawn, pourquoi ne pas faire une grande area "public" 300 Bloc autour, ouverte en partie aux bons buildeurs.

Je suis completement pour enlever moreore et l'armure mitrille, mais garder 3D_armor.

Je m'incline devant le fait de changer la rareté desur minerais, mais je persiste sur les grosses armure, les diminuer un peut leur ressitance et augmenter leur durabilite, pour le pvp, matt8fr : si le pvp est peut utiliser, c'est justement parce qu'on l'entere un maximum, moi je suis pour tout faire pour le déterer.

Je suis pour homedecor ou une alternative plus légère.

mgl512 : tu sais quoi ? On a cas aussi mètre le serveur en créatif et enlever toute difficulter, donner tous les privs a tous les joueurs et c'est eux qui règles tout, il faut comprendre qu'il faut imposer des limites aux joueurs sinon ils ne s'en imposeront pas.

Franchement paly2, arête de parler de MFF a chaque fois que tu veux changer un truc, tu seras toujours au dessous de MFF si tu ne tente pas ce qu'ils n'ont pas tenté, dans ta tete " si ça a foire chez eux, on ne le fait pas ", moi j'aurais pense " si ca a foire chez eux, on va s'en servir pour le faire différamment.

On attendre 0.5.0 stable pour reset.

Rajouter des objectifs serait copier MFF, encore une fois, aretez de tout faire comme eux.

Je suis complètement pour mettre le serveur UN PEUT plus difficile, sinon ( je l'ai déjà dit au dessus ) autant faire un serveur créatif.

Je suis pour rajouter en plus des broomstick, un bâton donnant fast une minute, mais vraiment super cher.

Je vais continuer de bosser sur les mini-jeux avec Upsilon a la rentree.

mega-gigaMynetest

**Comment by mega-gigaMynetest** [comment]
J'ai oublié Matfr, de faire un tri des joueurs avant de les envoyer sur la map est trop compliqué.

**Comment by matt8fr** [comment]
pour faire le trie on peux déjà envoyer les nouveaux dans le tuto du spawn, rien que cela découragerait les kikoos.

sur MFF il n'y a pas vraiment d'objectif, il y a des classes et des "quêtes" qui ne servent a rien.
mon idée serait plus de réaliser une seul quête pour débloquer 60% du jeux ! (ex: la quête débloque la possibilité de créer des areas, de miner le mithril,  de réalisé certain craft ...)

mega-giga je comprend la réticence de palige et mgl512 de toucher aux armures en effet il ne sont que 2,5 a géré toute la maintenance du serveur et déjà la c'est pas simple.

MFF est quand même une référence mega!!

**Comment by mega-gigaMynetest** [comment]
Il est vrai que la maintenance est pas simple, je ne l'avais pas vu de ce côté, et j'ai apprit récemment que Mynetest était a la base une copie de MFF en plus simple et moins lourds, donc je retire une grande partie de ce que j'ai dit plus haut.

En ce qui concerne le tri des kikoos je pensais qu'ils étaient déjà direct envoyé vers le tuto, si ce n'est pas le cas oui c'est une bonne idée.

**Comment by matt8fr** [comment]
Donc non pas encore, le tuto n'est pas complet ni corriger!

**Comment by Grossam** [comment]
Moi je suis pour garder les kikoos : c'est surtout grâce à eux qu'on rigole ;-)

Ce que je proposerais pour ne pas perdre les builds, serait d'ouvrir un nouveau serv à côté de l'ancien. Par un jeu de vases communiquant le vieux serv finirait par se vider doucement et par mourir de sa belle mort ou devenir un monde musée (solution qui n'interdit pas le transfert de builds). Ou alors faire cohabiter l'ancien Eurythmia (qui deviendrait "Eurythmia Junior", pour petites configs) et le nouveau ("Eurythmia +" ?)

En ce moment je suis peu sur Eurythmia car je n'ai plus rien à y découvrir. Je pense donc que le nouveau serv devrait avoir un max de biomes et être assez modulable pour offrir de la nouveauté de temps en temps (sous forme de mods maison ?). Moretrees, vines, des coraux, des algues… tout ce qui peu faire foisonner la végétation serait selon moi à adopter (MFF est bien côté végétation). Et des modes pour varier le sous sol (mais pas de nether : j'aime pas) ?

Concernant la difficulté, j'aime qu'elle ne soit pas trop élevé car le mélange des tranches d'âge fait, selon moi, la richesse de notre serv et de son ambiance. Mais peut-être que ceux qui le souhaitent pourraient avoir en jeu plus difficile avec des mobs plus puissant uniquement dans certaines zones ? Ou comme sur le vieil Axinit : plus on mine profond, plus ils sont costauds ? Sur le travelnet je rejoins matthieu : "pas assez cher mon fils !"

Pourquoi aussi ne pas envisager des protections plutôt que des areas ? En raréfiant un peu l'or, cela oblige à devenir vraiment riche pour avoir un grand domaine, et cela transforme automatiquement l'or en monnaie d'échange (ce qui crée une véritable économie). Chez Spo il faut de l'or et de l'étain pour crafter une protec, ce qui donne enfin une utilité à ce second minerai. Pour le nyan ? Pas d'opinion.

Ah ! Le mapgen ! J'aimais beaucoup celui du vieil Axi qui générait des rivières réalistes (ancien V7 ?) mais il ne serait plus utilisable; Je déteste le mapgen de MFF : trop biscornu et qui incite au grief (seul truc bien : des sous-sol animés avec des failles, des sources, de la lave, de l'acide…) Du coup je jetterai un oeil à Carpathian : quelqu'un peu m'indiquer comment l'ajouter chez moi pour l'utiliser en solo ?)

Je précise que je suis tout prêt à aider pour les tests, la modération, l'administration… du nouveau serv. Si on se lance dans des mods maisons, je tâte un peu de Blender, pas mal d'Inkscape et un petit chouille de LUA.


(PS : le tuto n'est pas complet (mea culpa) ceci dit il ne manque que la partie sur la mine).

**Comment by matt8fr** [comment]
@Grossam tu parle du tuto en ligne je pense, @mega-gigaMynetest  parle du tuto présent dans le bâtiment du spawn.

**Comment by mega-gigaMynetest** [comment]
Je suis assez contre ta façon de migrer, je préfèrais fermer le serveurs quelques jours le temps de bien tout préparer.

Je suis pour l'ajout des biomes, et contre remplacer area par protection, les joueurs se plaignent déjà assez d'avoir leurs maison grief, et ça ferait comme chez THELESHIT, des protections partout jusqu'a 2000 Block autour du spawn, de plus ce serait trop dur pour les admins de faire de grandes areas.

Je suis pour augmenter le prix de beaucoup de chose, mais pas les travelnets, soit on les enleve soit on les garde comme ça, 3 joueurs commençaient a faire un chemin horrible en pierre reliant 2 villes car ils n'avaient pas de quoi se faire des travelnets, je leurs aient dit d'enlever le chemin en échange de poser les travel reliant les deux villes.

Je parle effectivement du tuto du spawn, pas celui sur Google.

Un autre truc sur la mapgen : pas une map ou il faut aller en -10000 pour trouver un arbre, c'est insupportable, c'est comme si on avait 1000 couches de terre a creuser avant de pouvoir miner.

**Comment by matt8fr** [comment]
@mega-gigaMynetest  ! @Grossam  parle du formidable guide qui se trouve sur [notre site ](http://eurythmia.langg.net/premiers_pas.html)
1000 block pour trouver un arbre ça me fait pensé a axinit ! lol
c'est pour ça que je propose une foret public facilement accessible.

Pour relier des villes les modos pourront installer des travelnet public.

**Comment by mega-gigaMynetest** [comment]
Appart Docteur qui n'est pas spécialement pour, j'ai 10 votes oui et 0 votes non pour l'instant ( dont 4 votes de joueurs ) je pense que ca va arriver.

**Comment by Grossam** [comment]
Je voudrais essayé Carpathian. Mon client est en 4.17 et ce mapgen n'est pas dans la liste. Comment le rendre diponible ?

**Comment by paly2** [comment]
> Je voudrais essayé Carpathian. Mon client est en 4.17 et ce mapgen n'est pas dans la liste. Comment le rendre diponible ?

Carpathian ne sera disponible qu'à partir de 0.5.0-stable. Seule solution pour le tester actuellement: compiler la 0.5.0-dev et générer une map en singleplayer.

**Comment by Grossam** [comment]
Voui, mais pour cela il va falloir que je fasse un dis-upgrade pour passer à stretch…

**Comment by Grossam** [comment]
Et en ajoutant simplement les sources de Carpathian à la 4.17 avant de recompiler ?

**Comment by paly2** [comment]
> Et en ajoutant simplement les sources de Carpathian à la 4.17 avant de recompiler ?

Tu peux essayer de patcher ces deux commits, mais il y a beaucoup de chances pour qu'il y ait des conflits: https://github.com/minetest/minetest/commit/a80ecbee1e838491343af760539a37fac4232048 et https://github.com/minetest/minetest/commit/f871852f13db6072b3bffe25826d7520ef031ec0

```
git fetch origin master
git cherry-pick a80ecbe
git cherry-pick f871852
```

**Comment by Grossam** [comment]
Hier, je ne sais pas pourquoi, j'ai réussi à compiler la 0.5.0 avec mon GCC 4.9. Quand j'ai vu que ça bugguait en jeu, j'ai mis le répertoire à la corbeille. Là je viens d'y penser et de le récupérer (comme quoi faut jamais vider sa corbeille trop vite).

Je dispose don d'une 0.5.0 pour tester Carpathian. Je viens de l'essayer en activant Ethereal en plus, et on dirait que ça marche.

**Comment by mega-gigaMynetest** [comment]
Alors Etheral et Carpathian seraient compatibles ?! Je test ça des que je suis de retour a Paris, ce serait génial et réparerait plein de problèmes

**Comment by Grossam** [comment]
Sous réserve de tests plus poussés…

**Comment by paly2** [comment]
J'ai en effet regardé trop vite :-) Ethereal n'est pas un mapgenerator, il ne fait qu'enregistrer des biomes. C'est ensuite le mapgenerator qui prend en compte (ou non, comme v6 sur lequel Ethereal n'a aucun effet) les biomes enregistrés.

Carpathian est basé sur v7 qui supporte l'API Lua de registration des biomes. Carpathian la supporte donc aussi, et il est parfaitement compatible Ethereal. J'ai aussi testé, et le résultat est assez sympa.

**Comment by Grossam** [comment]
Bonne nouvelle ça !

Autre bonne nouvelle sur gitlab il y a des paquets pré-compilés de la 0.5, dont un .deb pour ma jessie. Mais, je voudrais l'installer à côté de la version stable qui est sur mon système, un peu comme un DRUN_IN_PLACE. C'est à ça que sert l'option --root de dpkg ?

Ceci-dit je vais pouvoir commencer à tester des mods.

**Comment by matt8fr** [comment]
[Woodcut](https://forum.minetest.net/viewtopic.php?f=11&t=18023) fonction t'il mieux que tree capitator ?

**Comment by mega-gigaMynetest** [comment]
En lisant un diagonale le forum, le mod a pas l'air finit, mais il faut tester

**Comment by paly2** [comment]
Woodcut n'est pas ce qu'il nous faut, ça n'est pas un dispositif anti-grief. Contrairement à treecapitator, il ne force pas la coupe de l'arbre entier.

**Comment by matt8fr** [comment]
OK :-)

**Comment by mega-gigaMynetest** [comment]
#131

**Comment by mega-gigaMynetest** [comment]
#130 *
