### ISSUE TITLE
Eurythmia Evo

### ISSUE THREAD

**Issue by matt8fr** [MT-Eurythmia/Eurythmia-server#126]
# Mods sur le serveur
si coché: mod supprimé ou remplacé ou bien si nouveau mod à ajouter)
si pas coché: mod actuellement sur le serveur et qui sera aussi sur le futur.

## Fournis avec minetest_game:

- [x] beds
- [x] boats
- [x] bones
- [x] bucket
- [x] carts
- [x] creative
- [x] default
- [x] doors
- [x] dye
- [ ] ~~farming~~ (The farming redo mod is loaded instead)
- [x] fire
- [x] flowers
- [x] give_initial_stuff
- [x] killme
- [x] screwdriver
- [x] sethome
- [x] sfinv
- [ ] stairs
- [ ] tnt
- [ ] vessels
- [ ] walls
- [ ] wool
- [ ] xpanes

## Autres mods:

- [x] 3d_armor
- [ ] areas
- [ ] automappercolors
- [ ] autoshutdown
- [ ] babelfish
- [ ] books
- [ ] broomstick
- [ ] brush
- [ ] chesttools
- [ ] christmas_craft
- [ ] death_messages
- [ ] easyvend
- [ ] email
- [ ] fail
- [ ] first_hour
- [ ] fishing
- [ ] gravitysuit
- [ ] h2omes
- [ ] hbarmor
- [ ] hbhunger
- [ ] hopper
- [ ] hudbars
- [ ] irc
- [ ] jumping
- [ ] landcraft
- [ ] lavasuit
- [ ] mapfix
- [ ] maptools
- [ ] markers
- [ ] mesecons
- [ ] metatools
- [ ] misc
- [ ] mob_horse
- [ ] mobs
- [ ] mobs_animal
- [ ] mobs_monster
- [ ] mobs_npc
- [ ] moremesecons
- [X] ~~moreores~~ ❌ 
- [ ] mtsatellite
- [ ] names_per_ip
- [ ] news
- [ ] nyantools
- [ ] pbj_pup
- [ ] pvpplus
- [ ] pw_like
- [ ] serveressentials
- [ ] shields
- [ ] signs_lib
- [ ] sneak_glitch
- [ ] sprint
- [ ] staffmagic
- [ ] stained_glass
- [ ] throwing
- [ ] throwing_arrows
- [ ] torch
- [ ] travelnet
- [ ] treecapitator
- [ ] u_skins
- [ ] unified_inventory
- [ ] vector_extras
- [ ] vivarium
- [ ] wieldview
- [ ] worldedit
- [ ] xban2
- [ ] ~~xdecor~~ ❌  [Homedecor](https://forum.minetest.net/viewtopic.php?f=11&t=2041) 🆕 

Mapgenerator: Carpathian

Mapgen mods to be *added*:

- [X] [Ethereal](https://forum.minetest.net/viewtopic.php?f=11&t=14638)
  - desactivate fiery (lava biome)
- [X] [Plantlife](https://forum.minetest.net/viewtopic.php?t=3898)
- [X] [More tree](https://forum.minetest.net/viewtopic.php?t=4394)

Mods à considerer/tester ?

- [ ] ~~[Ma & Pop's furniture](https://forum.minetest.net/viewtopic.php?f=9&t=17421)~~ ❌ [Homedecor](https://forum.minetest.net/viewtopic.php?f=11&t=2041)
- [X] [Unified Inventory Plus](https://forum.minetest.net/viewtopic.php?f=9&t=16615)
- [ ]  [Clay crafter](https://forum.minetest.net/viewtopic.php?t=13992) ?
- [X] [Protector](https://forum.minetest.net/viewtopic.php?id=4212)
- [ ] [Workbench](https://github.com/minetest-mods/workbench) **Custom fork indispensable**
- [ ] ~~[Enchanting](https://github.com/minetest-mods/enchanting) **Custom fork indispensable**~~ ❌
- [ ] [Technic Chests](https://github.com/minetest-mods/technic/tree/master/technic_chests)
- [ ] [soccer](https://forum.minetest.net/viewtopic.php?t=6104)
- [X] [Homedecor](https://forum.minetest.net/viewtopic.php?f=11&t=2041)

4. moderation/organisation:
- Garde t'on un spawn dans les aires ?
- Créer une grande zone de spawn avec foret, champs publique, commerce ...
- Pour le champs est la foret public je propose de ne placer qu'un spécimen de chaque mais qui ce replanterait automatiquement 2 ou 3 fois par jour. 

j’ajouterai vos proposition au fur et a mesure.

**Comment by Grossam** [comment]
Il faudrait qu'il y ait un max de biomes, pour rendre la carte agréable à explorer.

**Comment by fwhcat** [comment]
Pourquoi pas carrément utiliser ethereal qui vient avec 18 biomes:
https://github.com/tenplus1/ethereal/wiki

et les bones meal !

2017-08-25 14:40 GMT+02:00 Grossam <notifications@github.com>:

**Comment by Grossam** [comment]
Je crois qu'Upsi n'aime pas ce mod ?

**Comment by matt8fr** [comment]
je n'aime pas non-plus certain biomes d'ethereal.
la bones meal serait cool

**Comment by paly2** [comment]
Le problème d'Etheral, c'est que c'est une mapgen Lua, et que même avec LuaJIT les performances des mapgen Lua ne peuvent pas rivaliser avec celles des mapgen C++.
Après, ça peut valoir le coup. Le choix de la mapgen se jouera surtout entre Carpathian (nouvelle mapgen C++) et Etheral. N'hésitez pas à donner votre préférence !

**Comment by paly2** [comment]
Sinon, je suis assez d'accord pour ajouter les protections, plus simples et plus intuitives d'utilisation pour les joueurs. Cependant on conserverait les areas pour les modérateurs (la self-protection serait désactivée).

Je suis pour l'ajout de moretrees (et pour rassurer les modos, moi le premier: treecapitator est compatible moretrees).

**Comment by mega-gigaMynetest** [comment]
Pourquoi pas après tout protection, c'est tellement plus simple a manipuler quand tu connais pas bien le jeu, la complexité d'area pour ajouter un joueur...Combien de fois j'ai du expliquer comment utiliser in boundary bloc, car les commandes sont vraiment de la lune, mais oui il faut garder area pour les grandes zones comme le spawn ou les villes.

**Comment by mega-gigaMynetest** [comment]
Il est impossible de mettre et Caparthian et Etheral ? Entre les deux je choisirais quand même Caparthian, Etheral est utilisé par beaucoup de serveur, et Caparthian a l'air vraiment joli.

**Comment by Grossam** [comment]
Niveau mapgen, je pense que le truc a privilégié est la variété des biomes.

Mais comment ça marche ? La carte est générée à mesure qu'on découvre de nouveaux chunks ? Donc si beaucoup de joueurs explorent (surtout au début…) le serveur est très sollicité ?

D'où l'intérêt peut-être d'une phase de test privée qui permettrait à peut de  d'admin de construire en spawn tout en générant la partie centrale (la plus fréquentée) de la map ?

**Comment by paly2** [comment]
> Il est impossible de mettre et Caparthian et Etheral ?

Non, c'est impossible :-) On ne peut pas mélanger des mapgenerators

> Mais comment ça marche ? La carte est générée à mesure qu'on découvre de nouveaux chunks ? Donc si beaucoup de joueurs explorent (surtout au début…) le serveur est très sollicité ?

C'est exactement ça.

> D'où l'intérêt peut-être d'une phase de test privée qui permettrait à peut de d'admin de construire en spawn tout en générant la partie centrale (la plus fréquentée) de la map ?

Ouaip de toute façon le serveur ne serait pas ouvert pendant le transfert des bâtiments

**Comment by matt8fr** [comment]
n’allons pas trop vite en besogne, on planifie déjà quoi mettre dans la V2, comment se passera la migration? on verra par la suite.
je valide moreTree ? toujours avec tree capitator!

**Comment by Grossam** [comment]
TreeCapitator ne marche pas à tous les coups avec MoreTrees. Mais quand ça marche, ta hache est morte !

**Comment by paly2** [comment]
En fait, comme je l'ai expliqué sur #125, Carpathian et Ethereal sont capatibles.

Le problème d'Ethereal, c'est... les arbres.
![2017-08-27-121932_1920x1035_scrot](https://user-images.githubusercontent.com/12398822/29749024-2a95aeea-8b23-11e7-880c-212aae6933a9.png)
Ethereal génère des nombreuses variétés d'arbres (10 types d'arbres pour être exacts) dont beaucoup géants (exemple: séquoia, voir capture ci-dessus) et bien sûr pas du tout compatibles Treecapitator.
J'imagine déjà les forêts de séquoias volants, et je ne vois pas de solution pour l'empêcher.

**Comment by Grossam** [comment]
On peut peut-être "shunter" certains des arbres d'Ethereal ? Certains font double emploi avec Moretrees. Du coup on se retrouve avec des bouts de bois qui ont le même nom mais qui sont instackables…

Caverealms est peut-être un mod à essayer aussi ?

**Comment by mega-gigaMynetest** [comment]
Pourquoi ne pas supprimer le code des arbres qui ne fonctionnent pas du mod Etheral ?

**Comment by mega-gigaMynetest** [comment]
En ce qui concerne la forêt public on peut faire un système mesecon qui replante des que l'arbre est coupé, ou même un command bloc

**Comment by paly2** [comment]
> Caverealms est peut-être un mod à essayer aussi ?

J'ai peur que ça fasse un peu lourd, mais c'est vrai que c'est tout de même très tentant...
![2017-08-27-130451_1920x1035_scrot](https://user-images.githubusercontent.com/12398822/29749312-f059ed80-8b28-11e7-9e99-5c42a215b425.png)
![2017-08-27-130517_1920x1035_scrot](https://user-images.githubusercontent.com/12398822/29749314-f2a8ebe0-8b28-11e7-886d-e331faef94b3.png)
![2017-08-27-130800_1920x1035_scrot](https://user-images.githubusercontent.com/12398822/29749315-f4b6c8e4-8b28-11e7-9fb7-3ebaf7d6acac.png)

> Pourquoi ne pas supprimer le code des arbres qui ne fonctionnent pas du mod Etheral ?

Tous les arbres "fonctionnent" :) Ils sont simplement plusieurs à risquer de produire beaucoup de grief.
Possibilités:
* Laisser en l'état, faire confiance aux joueurs et corriger le grief à la main
* Tenter de rendre treecapitator compatible séquoias géants
* Rendre les troncs des séquoias géants des falling nodes
* Supprimer la génération des séquoias géants et ajouter un moyen d'obtenir leurs saplings (craft, drop...)

**Comment by matt8fr** [comment]
Caverealms à l'air cool mais le serveur tiendra t'il ? 

Pour les arbres la boom staff nous aidera. On pourra exploré les solutions une fois en jeux ?

**Comment by Grossam** [comment]
C'est qu'ils sont bien les sequoias j'ai toujours eu envie de faire une ville d'Elfes !

(Chez moi ils ne volent pas…)

**Comment by matt8fr** [comment]
Les sequoias géant sont créer a la génération de la map ? les saplings ne créer pas des sequoias aussi grand ?
si les réponses sont oui et oui, alors: Laisser en l'état, faire confiance aux joueurs et corriger le grief à la main semble une bonne solution.

**Comment by paly2** [comment]
> Les sequoias géant sont créer a la génération de la map ?

Oui
> les saplings ne créer pas des sequoias aussi grand ?

Si, ce sont les mêmes arbres. Mais s'ils ne sont pas générés et qu'ils sont plantés par les joueurs, il y en aura moins et donc moins de grief (surtout qu'ils devraient être majoritairement plantés dans des zones protégées)

> Pour xdecor: il faudrait un mod qui ajoute juste quelque meubles non ? et garder xdécor.

XDecor est buggé partout. Je préférerais ne pas le garder, et ajouter [enchanting](https://github.com/minetest-mods/enchanting) et [workbench](https://github.com/minetest-mods/workbench) sous forme de mods séparés.

 Pour la décoration, on peut partir sur [homedecor_modpack](https://github.com/minetest-mods/homedecor_modpack). Par contre il est très loin d'ajouter "juste quelques meubles" :p

**Comment by fwhcat** [comment]
Superbe ! J'adore homedecor il est bien plus complet que Xdecor !

Et sinon oui les séquoia géants peuvent monter haut, faut les planter par 4 (2x2) pour que ça soit énorme.

**Comment by Grossam** [comment]
+1 pour homedcor qui est très chouette

Matthieu m'a parler d'un "furniture" je ne sais quoi, je vais essayé de le retrouver.

Sinon, il y a un mod qui fait des portes de 3 de haut. J'ai pas le nom, mais ça manque des grandes portes (et un mod pour des portes de taille illimitée ?)

**Comment by mega-gigaMynetest** [comment]
+1 pour homedecor

**Comment by paly2** [comment]
Issue transférée vers https://github.com/MT-Eurythmia/Eurythmia-Evolution/issues/1
