### ISSUE TITLE
Les hopper réparent les items

### ISSUE THREAD

**Issue by mega-gigaMynetest** [MT-Eurythmia/Eurythmia-server#127]
Si on met un hopper sous un coffre, que l'on met un item casse dans le coffre, on va le retrouver réparer dans le hopper au bout de quelques secondes sans utiliser de marteaux.
Je ne comprend pas, faut regarder la dernière mise a jour des hopper si c'est la dedans, ou alors un bug.

**Comment by mega-gigaMynetest** [comment]
Réparer

**Comment by paly2** [comment]
Mais pas encore mergé (https://github.com/minetest-mods/hopper/pull/10)

**Comment by mega-gigaMynetest** [comment]
Bah, de ce que j'ai teste ça réparé plus
