### ISSUE TITLE
Base de données de `names_per_ip` effacée

### ISSUE THREAD

**Issue by mega-gigaMynetest** [MT-Eurythmia/Eurythmia-server#128]
Tous les joueurs ayant un last login d'avant août ( dont Docteur) répondent " no entry for " lorsque je fais /ipnames whois.
Au début j'ai pensé a une base xban encore detruite, mais, quand je fais /xban_record de le_lepine_95 qui a eu un ban de test début juillet, ça me met le ban.
Quand je regarde son ip ça me dit qu'il n'est jamais venu.
La je bloque...Je vois pas ce que c'est.

**Comment by paly2** [comment]
Les bases de données de names_per_ip et d'xban2 ne sont pas partagées.

Il se peut toutefois que cela soit lié au même bug que les corruptions de la base xban2. Dans ce cas, le bug se trouverait dans une fonction d'un niveau inférieur, dans l'engine vraisemblablement.

**Comment by mega-gigaMynetest** [comment]
Bon, on peut pas y faire grand chose
