### ISSUE TITLE
Nom de l'Eurythmia v2

### ISSUE THREAD

**Issue by paly2** [MT-Eurythmia/Eurythmia-server#129]
Lorsque Mynetest a été renommé en Eurythmia, vous avez été nombreux à vous en plaindre :-)

Puisqu'un "Eurythmia v2" devrait être ouvert, autant en profiter pour choisir un nouveau nom ! Postez vos propositions ici !

**Comment by matt8fr** [comment]
Perso je commence à m'habituer à Eurytmia lol
Minebury ? :_)

**Comment by Grossam** [comment]
Moi je vote pour… Eurythmia ! J'ai fini par m'y faire. Pour le distinguer de l'autre, je trouve ce v2 pas très poétique. Pourquoi pas Eurythmia Evolution, Eurythmia Nouveau Monde, Eurythmia Eden,… ?

**Comment by matt8fr** [comment]
Eurythmia Évolution ça sonne bien ! EE pour les intimes.

**Comment by fwhcat** [comment]
Pourquoi pas Schmilblick ? 🤣

**Comment by paly2** [comment]
Ou alors Eurythmia Metempsychosis (lol) ? Eurythmia Zenith (qui suppose que la première version était le "sunrise"...) ?

**Comment by mega-gigaMynetest** [comment]
Pourquoi pas Eurythenticonstitutionnellement ?

**Comment by Grossam** [comment]
Désoxyrythmianucléique ? Acide acétyleurythmiasalicylique ?

**Comment by paly2** [comment]
Donc on reste sur Eurythmia Evolution ?

**Comment by matt8fr** [comment]
EE validé ! Une fois . . .

**Comment by fwhcat** [comment]
Eurythmia Evolution
comme ça la prochaine migration ce sera
Eurythmia Revolution 👍

**Comment by Grossam** [comment]
Yes ! Il ouvre quand le serveur de test ?

**Comment by mega-gigaMynetest** [comment]
Va pour Eurythmia Evolution.

Je crois que le serveur de test ne pourra ouvrir qu'en 0.5.0 stable. Mais on peut tester en solo

**Comment by Grossam** [comment]
OK pour les tests en solo : j'ai déjà commencé à bidouiller. Que faudrait-il tester en priorité ? Chercher la bonne graine pour un monde sympa ?

Sinon, Valleys serait peut-être à considéré ? Il fait des rivières qui coulent…

**Comment by fwhcat** [comment]
@Grossam, ton commentaire est hors-sujet, ce ticket concerne uniquement le changement de nom :)

La décision ayant été prise de l'appeler Eurythmia Evolution, je ferme le ticket.
