### ISSUE TITLE
Gardons les Issues pour les issues => Gitter pour les conversations

### ISSUE THREAD

**Issue by fwhcat** [MT-Eurythmia/Eurythmia-server#130]
Privilégions les conversations autour du projet sur: https://gitter.im/MT-Eurythmia/Lobby
Cela permet de ne pas "polluer" les issues GitHub, et nous permettra de discuter autour du projet.

**Comment by paly2** [comment]
Excellente idée!

**Comment by fwhcat** [comment]
Je regarde comment mettre un badge sur le Readme du projet comme lien vers le Gitter.

**Comment by fwhcat** [comment]
Fixed : 3bd39bc8e0a086f81f2440f504f805dc5fcde24e
