### ISSUE TITLE
Shared door?

### ISSUE THREAD

**Issue by fwhcat** [MT-Eurythmia/Eurythmia-server#21]
Idée: créer une shared door que tous les gens de l'area peuvent ouvrir. On pourrait reprendre la steeldoor mais la mettre en violet comme les shared chest.
Je vais regarder comment faire ça.

**Comment by paly2** [comment]
Problème, sans-doute: choisir les noms nécessite un formspec, or les formspec s'ouvrent en faisant des clics droits. Par conséquent, qui de la porte ou du formspec doit s'ouvrir au clic droit ?

Il y a sans-doute moyen de contourner ça, en ajoutant par exemple la nécessité d'appuyer sur SNEAK pour ouvrir le formspec.

**Comment by mgl512** [comment]
Les gens de l'area peuvent déjà ouvrir les portes en fer en utilisant des object de mesecons comme la torche, les leviers etc. Ils peuvent poser une torche devant la porte ou la trappe => elle s'ouvre. Ils cassent l'objet pour la refermer. On utilisait ça au QG des Mithrils sur MFF1. It's not a bug, it's a feature.

**Comment by mgl512** [comment]
La clé de minetest_game faite à partir de default:skeleton _key ne résout pas ça ? Elle est pas encore top parce qu'on ne sait pas les portes de qui elle ouvre. Un joueur partage toutes ses portes en donnant une clé à un autre.
