### ISSUE TITLE
Demande de mod

### ISSUE THREAD

**Issue by matt8fr** [MT-Eurythmia/Eurythmia-server#54]
Suite aux recommandations d'AcidDragon je poste ici ma demande.

Gérer une ville sur un serveur n'est pas facile, modération, grief, areas...
Donc voilà pour WoodBury cela me serait utile mais d'autres y trouveront une utilité.

J'aimerais un mod qui pourrait s'appeler: city manager.
Avec ce mod on peut donner le priv mayor à un joueur qui crée une ville, ce joueur peut nommer des adjoints, les maires et adjoints ont accès à un bloc semblable au bundary pour gérer les habitants de la ville (créer un spawn de la ville, ajouter un joueur dans la ville, lier une area à la ville, gérer les métiers...).

En plus de cela j'aimerais un bock cliquable pour réaliser des quêtes, le maire pose le block où il veut, le numérote (quête 1puis 2 puis 3 ....).

J'ai conscience qu'un tel mod demanderait un travail de fou, mais ça serait trop cool.
-matthieu8fr-

**Comment by mgl512** [comment]
Salut matthieu. Je suis Le_Docteur. paly2 est Upsilon et AcidNinjaFWHR est AcidDragon. C'est le bon endroit pour poster ce genre de requête. Si ce truc finit par être écrit, les quêtes seront surement un mod indépendant de l'administration d'une ville.

**Comment by paly2** [comment]
Salut @matt8fr, bienvenue sur GitHub !

Donc d'après ta description j'imagine un mod semblable à areas, dans lequel une area est une ville (ce type d'area ne pouvant être créé que par les admins). À chaque ville, l'admin associe un mayer, qui est le seul à pouvoir créer des areas (banales, du mod areas) dans la ville. L'interact n'est possible dans la ville que par certains joueurs, décidés par le mayer, au moyen d'une commande `/add_inhabitant <player>`. Une commande `/townspawn` est ajoutée, qui permet à un joueur qui la tape de se téléporter au spawn de la ville dans laquelle il se trouve (la commande retournant un message d'erreur s'il ne se trouve dans aucune ville).
Pour les quêtes et les métiers (qui restent assez vagues dans ton commentaire), c'est un aspect beaucoup plus complexe qui ne sera sans-doute abordé qu'une fois que tout ce qui est décrit ci-dessus fonctionnera bien.

Réponds à ce post en corrigeant tout ce que j'ai mal compris et en ajoutant ce que j'ai oublié, puis on pourra s'attaquer au développement !

**Comment by matt8fr** [comment]
Oui mgl512 je pensais aussi que le mod quêtes serait dissocier de la gestion de ville.
Merci pali2 
Je pensais que le mod aurait pu utiliser les areas créer avec le mod area mais dans les deux cas le fonctionnement finale est le même: des areas :-)
tous le reste c'est ça ! avec pourquoi pas un block pour la gestion des ajouts de joueurs et autre

**Comment by matt8fr** [comment]
Pour les quêtes je suis tomber sur ce [mod](https://forum.minetest.net/viewtopic.php?f=9&t=14227) qu'il faudrait tester voire adapté.
Pour la gestion de ville dsl je n'est pas trouver de mods proche du bute rechercher il va donc falloir tout coder. (il y a bien le[ mod faction](https://forum.minetest.net/viewtopic.php?f=11&t=5919) qui gère l’appartenance des joueurs a un groupe mais pas pour une ville)
je ne sais pas programmer alors a vous de jouer!
et merci d'avance.
matt

**Comment by mgl512** [comment]
On a utilisé factions sur MFF1, celui qui était vraiment fun, avec les factions rivales Les_Mithrils et I_lick_diamonds_(And_I_am_proud_of_it). Ça ne marche pas. A part appartenir à une faction ou révoquer ses membres, il n'y avait rien. Même le chat uniquement entre membres d'une faction, la chose censée être la plus utile, ne marche pas (voire il crashe le serveur). On donnait accès aux aréas de la faction avec les commandes d'areas. On révoquait l'accès de la même manière. 

"factions" utilisé pour Woodbury donnerait une faction de bucherons par exemple, qui pourrraient se parler entre eux sur un canal privé si on corrigeait le chat. Pareil pour les mineurs. Et peut-etre une faction Woodbury qui regrouperait toutes les castes. Mais ce n'est pas interne à une ville. Les castes devraient s'appeler woodbury, woodbury_bucherons, woodbury_mineurs etc si on veut pouvoir avoir d'autres villes. Avec tous ces noms en plus court parce qu'ils sont utilisés comme paramètres du chat: /f woodbury_bucherons message

**Comment by matt8fr** [comment]
Donc c'est pas une si mauvaise idée de modifier/intégrer une partie du mods faction enfin: Tu le voie en plus du mods de gestion de ville ou intégré?

**Comment by mgl512** [comment]
"factions" ne servait vraiment à rien comme c'était sur MFF1. Un mod qui intégrerait factions + possibilité de faire des areas de faction + un spawn serait surement mieux. On aurait déjà pu avoir les habitants d'Epase, les élèves de Poudlard, les habitants de toutes les iles volantes etc. 

factions + spawn + canal de chat de faction serait surement un bon début.

**Comment by AcidNinjaFWHR** [comment]
Cela me parait trop compliqué à développer et surtout trop couteux en temps. Faudrait que tu proposes une liste de petites choses qu'on pourrait faire pour commencer, et aller au fur et à mesure à quelquechose qui te convienne.

1) respawn dans le spawn de la ville si on est dans une ville
2) ajouter un joueur dans une ville c'est quoi, ça lui donne interact dans la ville? ça lui attribue un emplacement pour y batir sa maison? (une area)

Pour le chat je crois qu'on peut le limiter à un certain rayon autour de nous, à voir...

**Comment by mgl512** [comment]
Moi aussi ça me parait compliqué et je voudrais voir comment ça se passe en jeu pour un joueur test qui veut rejoindre Woodbury. Avec ce qu'on a actuellement, il demande à matthieu dans le chat. matthieu va à Woodbury par son téléporteur personnel. Il invite le joueur à se téléporter sur lui, il lui fait une area sur une parcelle. Un admin créé un téléporteur personnel pour Woodbury dans la maison classique de ce joueur. 

Je suppose que ce qu'on voudrait, c'est que le joueur postule par chatcommand de "factions". Quand il est accepté par le chef de faction, il obtient la possibilité de se téléporter au spawn de woodbury. Il devra attendre ensuite que matthieu lui fasse une area sur une parcelle (ou lui donne accès à toute l'area de Woodbury mais je suppose que ce n'est pas ce que matthieu veut) 

Et c'est fini pour le moment parce que ça devient vraiment compliqué et obscur. Le joueur ne peut pas rejoindre de faction de bucherons, de mineurs, fermiers à Woodbury. D'après ce que je comprends, ce sont des métiers exclusifs. Je ne sais pas si on pourra forcer ça un minimum par codage mais je suppose qu'il doit y avoir beaucoup de roleplay parce qu'un joueur fermier peut toujours aller couper du bois ou miner hors de Woodbury au lieu d'échanger les produits de sa ferme contre ces marchandises. La caste des mineurs a le problème que ses ressources sont épuisables. Des /deleteblocks peuvent aider à restaurer les minerais avec certains risques.

**Comment by matt8fr** [comment]
Je me doutait bien que l'on visait trop haut ! 
donc oui pour faire simple, comme le propose Le_Doc / mgl512: ont peux utiliser une partis du mod faction pour gérer l’appartenance d'un joueur a la ville(par la suite les nouveau joueur spawneront directement a WoodBury, si les dieux du serveur son tous dac!).
Pour les métiers, seul les bucherons auront accès a l'area de la foret, le reste de la ville étant protéger et je vais réaliser une muraille en rondin autour de la ville mais oui il faudra que les habitants joue le jeu!
Pour ca il nous faudrait aussi le mod de commerce qu'AcidDragon a installer sur son serveur pour le marché.
Pour la mine on peux descendre très profond avant d’être a court de minerais.

**Comment by paly2** [comment]
Voici une liste de choses à faire au fur et à mesure pour le développement (j'invite tout le monde à proposer des modifications) :
* Point de départ: une sorte de mod faction, contenant initialement un propriétaire associé, et des membres. Le(s) propriétaire(s) peu(ven)t ajouter des propriétaires ou des membres. Seul un modérateur possédant le privilège adéquat peut créer une faction, en y associant forcément un propriétaire initial.
* Ajout au mod la possibilité de créer une faction-area par faction (on peut sans-doute reprendre du code d'areas), sans que celle-ci pour le moment dispose de la moindre fonctionnalité (elle est simplement correctement sauvegardée et la possibilité pour ce propriétaire d'y ajouter des membres) et affichée dans le HUD).
* Ajout de la fonctionnalité du chat à la faction-area: un message commençant par une apostrophe, envoyé dans la faction-area par un joueur qui en est membre, n'est reçu que par les joueurs membres de la faction.
* Override de `minetest.is_protected` pour n'autoriser qu'aux joueurs membres de la faction l'interact dans la faction-area
* D'autres choses nécessaires ??

**Comment by matt8fr** [comment]
c'est déjà un bon point de départ, question: utile ou pas? une différenciation entre les différente aréa-faction,
pour les parcelles, lieux pour les jobs, bâtiments publique,....

**Comment by matt8fr** [comment]
après un test avec 3 habitant finalement la ville fonctionne correctement sans mod même si les manipe pour atribuer un terrain, une chambre a l'auberge ... aurait pu être simplifier par ce mod.
étant donné que le mod n'est de toute évidence pas prés de sortir je vous demande s'il vous voulais continuer?
de plus j'ai une envie d'un autre mod bien plus simple a faire( pour les partis de dé a coudre)
merci a vous quand même !

**Comment by paly2** [comment]
> de plus j'ai une envie d'un autre mod bien plus simple a faire( pour les partis de dé a coudre)

En quoi consiste ce mod exactement ?

> je vous demande s'il vous voulais continuer?

On laisse l'issue ouverte pour le moment, pour rappeler qu'il faut faire le mod :-)

**Comment by matt8fr** [comment]
Voici les règles du dé a coudre :[ ici](http://minecraft-fr.gamepedia.com/D%C3%A9_%C3%A0_coudre)
mais une partie en jeux est plus parlant .

**Comment by paly2** [comment]
Donc, c'est une copie d'un mod de Minecraft... Je préfère les nouvelles idées. Mais je vais y travailler.

**Comment by matt8fr** [comment]
alors oui c'est un jeux qui vient de la communauté Minecraft mais je ne crois pas qu'il y est de mod même sur Minecraft. on prépare une partie jeux a WoodBury alors ne t'en fait pas on va en inventé aussi des mini jeux!

**Comment by matt8fr** [comment]
quelqu'un sais si un mod apporte[ ca](https://www.youtube.com/watch?v=Y97oSbnNEcI) sur Minetest?

**Comment by mgl512** [comment]
Jamais vu ça. C'est sélectif sur les blocs que ça enlève (j'ai vu pierre, bois, terre mais pas minerais ni laine). Ça détermine le plan de départ de minage selon l'angle avec lequel le joueur regarde on dirait, vertical sur sa cible et horizontal au sol. C'est plus rapide que de le faire avec worldedit mais je n'ai jamais vu de mod similaire sur Minetest.

**Comment by matt8fr** [comment]
si tu clique sur de la stone ça enlève juste la stone dans la zone d'action de la pioche,
non pas d'angle ou autre juste 0 a 5 block autour du block cliquer sphere ou cube selon la config de la pioche.
effectivement pour le grief c'est du rapide avec ce genre de pioche !
un autre mod pour rêver dans le [térraforming](https://www.youtube.com/watch?v=ti_N1nDKq_k) !

**Comment by matt8fr** [comment]
@paly2 tu pourait extraire l'outil "boom staff" de magicstaff ? c'est l'outil qu'il nous faudrait 🙏 
il ne se règle pas par commande mais en fonction du nombre de blocs de mese présent dans l'inventaire sous l'outil.

**Comment by paly2** [comment]
@matt8fr pourrais-tu donner un lien de téléchargement de ce mod ? Après recherche sur le forum, je n'ai trouvé que https://forum.minetest.net/viewtopic.php?id=3884, qui est très vieux (2012) et ne propose pas de tel outil.

**Comment by matt8fr** [comment]
dsl j'avais bien copier l'adresse mais j'ai oublier de la coller lol[ voila](https://github.com/taikedz/vivarium) !

**Comment by paly2** [comment]
https://github.com/MT-Eurythmia/Eurythmia-server/commit/e965fb24a2588365407175f2dd0f866f6cc14ea4 😃

**Comment by matt8fr** [comment]
Merci mais.... ça ne marche pas ! 😃
Les outils sont bien la mais quand on clique rien ne se passe, il n'y a pas non-plus les message du chat au moment du clique.
bizarre

**Comment by mega-gigaMynetest** [comment]
une question permit tant d'autres...que fout cette issue encore ouverte ?

**Comment by mega-gigaMynetest** [comment]
oh ce failclic ultime, je voulais pas mettre ça ici xDDD dsl
