### ISSUE TITLE
Base xban2 encore détruite

### ISSUE THREAD

**Issue by mgl512** [MT-Eurythmia/Eurythmia-server#79]
`2017-02-21 18:45:04: WARNING[Main]: [xban] Unable to load database: Deserialization failed: unknown error`

Le détail de l'erreur est vraiment un plus lol

EDIT: Depuis le temps la sauvegarde hebdomadaire, s'il y en avait une, a dû être effacée par la base vide...

**Comment by mgl512** [comment]
C'est avec un grande joie que j'annonce que la base xban a été, _encore une fois_, détruite. Mais pour la première fois de l'histoire de Mynetest (je pense), on a une ligne d'erreurs avec plein de mots:

`2017-05-16 19:17:47: WARNING[Main]: [xban] Unable to load database: Deserialization failed: (load):1: unexpected symbol near '<'`

**Comment by mgl512** [comment]
C'est pas possible de restaurer une sauvegarde hebdomadaire ?

**Comment by paly2** [comment]
Si, je le fais

**Comment by mgl512** [comment]
Encore détruite à jamais probablement :(
