### ISSUE TITLE
PVP

### ISSUE THREAD

**Issue by matt8fr** [MT-Eurythmia/Eurythmia-server#90]
Il y a plusieurs soucis avec le PVP et le mod PVPplus:

il fraudais un son au moment ou la cmd /tournament est lancé pour indiquer au joueurs qu'un tournois commence, je pense que le message dans le chat passe parfois inaperçus dans un flux de chat parfois conséquent.

du coup 60 sec pour dire a tout les joueur de faire /engage pour faire du pvp est trop juste.

après avoirs tester un tournois avec swag et caramel il me semble il en ressort que ni moi ni caramel ne soit mort durant le tournois, pourtant on est presque rester l'un devant l'autre a se taper dessus,
lui armure diams épée mithril et moi armure mithril épée nyan, je ne lui est infliger aucun dégâts.

swag sans armure est mort en moins d'une minute.

**Comment by mgl512** [comment]
Pour le chat, la plupart du temps je ne remarque un tournoi que dans les 5 dernières secondes d'enregistrement parce qu'il y a une avalanche de messages d'avertissement qui arrivent. Mais c'est normal je pense parce que tout le monde me demande tout le temps des trucs et j'ai du mal à suivre le chat.

Pour le combat en armure, c'est normal. Le PvP en armure ne se finit presque jamais par la mort de l'un des joueurs sauf si l'un des participants est un noob, même sur les autres serveurs. J'ai eu des combats contre Sauron et son frère sur Axinite (à l'époque où ils étaient "méchants") qui se sont toujours finis par la téléportation de celui qui était le plus en difficulté. MFF a essayé de se dédier au PvP et c'est un fiasco total. Ils n'ont fait que lutter contre les joueurs et contre tout ce qui est pratique. Les mobs super-endurants qui tuent en un coup viennent de ça, le stuff éparpillé et perdu à jamais aussi, tout ce qui est détestable sur leur serveur. Je suggère de ne surtout rien faire pour améliorer le PvP. C'est aux joueurs de fixer des règles de combat. Sur Axinite, ils font des tournois avec stuff précis et commun à tout le monde, comme pas d'armure et épée mese. Ceux qui ne respectent pas ce stuff ne participent pas. L'arbitrage se fait par un joueur ou un modérateur. Ils ont déjà modifié les monstres, qui sont très endurants et usent énormément les épées. C'est déjà une peine de miner dans des grottes chez eux. Ils ont créé la mana pour les commandes comme /spawn, qui est plutôt impopulaire. Ils se MMFisent. Je n'ai rien vu qui soit fait en faveur du PvP qui ne soit pas devenu une nuisance pour le jeu. 

En pratique, modifier les armes et les armure causerait encore plus de maintenance. Je trouve qu'on a déjà trop de mods à maintenir nous-mêmes. Et tous ceux qui ont fait ça avant nous ont pourri leur serveur.

**Comment by matt8fr** [comment]
voila pourquoi un jingle genre 'PVP!!!!!' bien fort dans les oreilles serait plus 'visible'.

je ne pensait pas non-plus modifier les armes et armures
mais si le mod pvpplus pouvait vider l'inventaire puis donner un stuff identique a tous le combat serait plus équitable!

**Comment by paly2** [comment]
Un son est une bonne idée, j'invite tous les joueurs qui s'y connaissent dans ce domaine à proposer des sons!

> mais si le mod pvpplus pouvait vider l'inventaire puis donner un stuff identique a tous le combat serait plus équitable!

Je suis tout à fait d'accord, mais c'est compliqué, sinon impossible. Cela implique en effet d'interdire aux joueurs de modifier le contenu de leur inventaire pendant le tournoi (afin qu'ils ne gardent pas les armes qui leur sont fournies et qu'ils ne se remettent pas d'armure après que le tournoi aie commencé), et ça n'est pas possible avec l'API actuelle de Minetest - du moins pas à ma connaissance, peut-être qu'il y a des hacks pour faire ça :p

**Comment by matt8fr** [comment]
Pour le sons je vais passer le message,
Si le tournoi se déroule dans la zone natural arena je vois pas comment ils pourrai obtenir/caché une armure, pareille pour l'arène de woodbury.
Le mod bones arrive à vidé l'inventaire dans un 'coffre' Ça doit être faisable. 
Si on doit demander à tout les joueurs de se conformer au stuff défini on s'en sortira pas .

**Comment by paly2** [comment]
> Si le tournoi se déroule dans la zone natural arena je vois pas comment ils pourrai obtenir/caché une armure, pareille pour l'arène de woodbury.

Oui, mais les joueurs peuvent quand même démarrer un faux tournoi en dehors de ces arènes et garder le stuff qui est donné par le mod...

> Le mod bones arrive à vidé l'inventaire dans un 'coffre' Ça doit être faisable.

Il serait plus simple pour le mod d'enregistrer le stuff quand il le supprime - y compris dans un fichier sur le disque, au cas où il y ait un crash - et le remette dans l'inventaire à la fin du tournoi.

**Comment by paly2** [comment]
Pour choisir le temps de départ du tournois: https://github.com/Mynetest/pvpplus/commit/74dd23f7c63bdca631d7f0636af4a2cd7814b175

**Comment by paly2** [comment]
Des sons ont été ajoutés: https://github.com/Mynetest/pvpplus/commit/5b6f9ddb54381856a2d5ccd2faa616476c1a52d5

**Comment by matt8fr** [comment]
après teste, les sons apporte un vrais plus !!! la au-moins, il y a tout le monde qui dit: "c'est quoi ce sons ?"
et la musique ambiance durant le combat et parfaite !!!
tu a des idées a venir pour la suite du mod ?

**Comment by paly2** [comment]
> tu a des idées a venir pour la suite du mod ?

Pas pour le moment, mais j'aimerais trouver une idée viable pour la question du stuff

**Comment by matt8fr** [comment]
j'ai vue que tu avais dans ta TO DO liste : Add a HUD for the tournament score
j’attends  çà avec impatience !!
pour le stuff JAPP a proposer un stuff qui a une duré de vie dans le temps ! (10min ?)

**Comment by paly2** [comment]
> pour le stuff JAPP a proposé un stuff qui a une durée de vie limitée dans le temps ! (10min ?)

C'est une bonne idée, mais, hélas, l'engine ne propose rien pour contrôler la durée de vie d'un item. Et cette fonctionnalité est à peine plus simple à implémenter qu'un contrôle de l'inventaire du client (qui nécessiterait une modification du protocole non rétro-compatible), dès qu'elle doit prendre en compte la copie et le déplacement des items (même si théoriquement, c'est faisable, en ajoutant des callbacks `on_item_move`, `on_item_create` et `on_item_delete` par exemple, ce qui permettrait au mod de contrôler où sont les items possédant un lifetime, et des fonctions `record_item_moving`,`record_item_creating`, `record_item_deleting` qui permettraient aux mods de signaler que le callback correspondant doit être appelé).

**Comment by matt8fr** [comment]
A ce que je comprend il n'y à rien de prévu de basse dans l'engine pour faire ça mais en bidouillant c'est faisable (Mais compliqué!)

Y'a t'il une possibilité de téléporter tout les joueurs en lançant un globale tournament ? /start_global_tournament teleport ?

**Comment by paly2** [comment]
> Y'a t'il une possibilité de téléporter tout les joueurs en lançant un globale tournament ? /start_global_tournament teleport ?

Non, ou bien manuellement avec `/teleport` :-) La commande ne le propose pas elle-même car elle démarre immédiatement le tournois, ce qui aurait pour conséquence de téléporter tous les joueurs au même endroit au moment où le tournois commence (ils n'auraient pas le temps de s'éloigner comme avec `/tournament teleport`).

**Comment by matt8fr** [comment]
>ce qui aurait pour conséquence de téléporter tous les joueurs au même endroit au moment où le tournois commence ,ils n'auraient pas le temps de s'éloigner.

Sauf si le PvP n’était activer que 10 sec après la téléportation.

**Comment by paly2** [comment]
> IL y a un soucis aussi, a la mort des joueur, ils respawn au spawn ou a leur lit et demande souvent a être TP pour récupéré leur os...

https://github.com/Mynetest/pvpplus/commit/3b6ff71bc2f94080435e70e0665a0598e4105ac1

Le stuff est maintenant automatiquement remis dans l'inventaire du joueur 😃 J'avoue cependant que je vois là arriver une nouvelle vague d'usebug, avec des tournois factices pour ne pas perdre de stuff...

**Comment by matt8fr** [comment]
Tu veux dire lancer un tournois sans faire vraiment de PvP pour au cas ou on meurt en minant par exemple ?
Question subsidiaire: Comment se termine un tournois ? temps écoulé? points max?

**Comment by paly2** [comment]
> Tu veux dire lancer un tournois sans faire vraiment de PvP pour au cas ou on meurt en minant par exemple ?

Oui 😕 

> Question subsidiaire: Comment se termine un tournois ? temps écoulé? points max?

Il se termine quand il n'y a plus qu'un seul joueur dans le tournoi. Un joueur peut quitter le tournoi en mourant, en quittant le jeu, en tapant `/leave_tournament`, ou en se faisant retirer par un modérateur de tournoi qui a tapé `/remove_from_tournament`.

**Comment by matt8fr** [comment]
peut-être faut il ajouter un délai de fin de partis ? 
par défaut si un joueur lambda lance un tournois il dure 10 ou 15 min max 
si c'est un joueur qui a le privs tournament c'est un tournois a mort !

**Comment by matt8fr** [comment]
l'autre jour, deux joueurs lancer des tournois a répétition cela flooder le chat, une solution?

**Comment by paly2** [comment]
> l'autre jour, deux joueurs lancer des tournois a répétition cela flooder le chat, une solution?

Je vois deux possibilités de solution:
* Un privilège (donné par défaut) autorisant à lancer des tournois. Ce privilège pourrait ainsi être retiré aux joueurs qui s'en servent pour flooder. Un callback resterait pendant un mois dans le mod `misc` pour donner ce privilège aux comptes existant déjà qui ne l'ont pas.
* Un timing limitant le temps entre plusieurs lancers de tournois infructueux consécutifs.

**Comment by matt8fr** [comment]
Je ne pense pas qu'ils le faisait dans l'intention de flooder mais enchainer juste tournoi sur tournoi! sans armure ça ne dure pas donc ...
le timing me semble bien, exemple: pas plus de 3 partis par heur 
le privs semble pas mal aussi, je pense aussi en terme de sanction( tu embête tel personne on te retire le privs une semaine)

**Comment by paly2** [comment]
> j'ai vue que tu avais dans ta TO DO liste : Add a HUD for the tournament score
j’attends çà avec impatience !!

C'est fait :-) https://github.com/Mynetest/pvpplus/commit/cc2724d67b627cc800668642a5c6b09a5ec754f0
Le HUD s'affiche mieux avec une police monospace, comme le tableau des scores. Cependant (au contraire du tableau des scores...) il reste bien lisible même si ça n'est pas le cas, mais mal aligné.

**Comment by paly2** [comment]
> l'autre jour, deux joueurs lancer des tournois a répétition cela flooder le chat, une solution?

C'est finalement la troisième solution que j'ai choisi 😃 
Les messages ne peuvent être envoyés en broadcast que par les joueurs possédant le privilège `tournament_mod`, et seulement s'ils ajoutent l'option `broadcast` à la commande /tournament.

Autrement, le décompte (et le messages d'alerte 10 secondes avant le tournoi) n'est envoyé qu'aux joueurs s'étant engagés ; et les messages de suppression (ou plus rarement d'ajout, si un modérateur de tournoi utilise /add_to_tournament) ainsi que le tableau des scores ne sont envoyés qu'aux joueurs qui jouent ou ont joué le tournoi. Au final, le seul message envoyé aux joueurs qui ne souhaitent pas jouer le tournoi est le message d'annonce de l'ouverture, en même temps que le son.

**Comment by matt8fr** [comment]
parfait ! je vais tenter de mettre a jour la doc au spawn et sur le site !

**Comment by matt8fr** [comment]
Hier il y avait un bug avec le mod, après avoir lancer /tournament le /engage renvoyer une erreur pas de tournois, /tournament_info trouver bien le fameux tournois!
j'ai fait un /error et après reboot tout a refonctionner.  
Je voulais savoir également si tu avais prévue par la suite de faire d'autre mod de jeux? 
Si oui seront il intégré dans le mod PvPplus ?

**Comment by paly2** [comment]
> Je voulais savoir également si tu avais prévue par la suite de faire d'autre mod de jeux?
> Si oui seront il intégré dans le mod PvPplus ?

Non, mais si quelqu'un a des idées pour compléter ce mod PvPPlus, je suis tout ouïe 😃

**Comment by matt8fr** [comment]
il y a toujours le soucis d'équité, un joueur en full mithril est sur de gagner, si il y en a deux le combat dure des plombes !

j'ai pensée a un mini-jeux, le sumo-test (mysumo, comme on veux):
Deux joueurs ou plus s’affronte sur une plateforme (6, 10 cubes de coté) le bute est de pousser l'autre hors de la plateforme  avec pourquoi pas un bouclier spécial qui fait reculer les joueurs toucher.

**Comment by matt8fr** [comment]
D'autre idées:
-un joueurs qui ne bouge plus pendant 5 ou 10 sec prend des dégâts pour l'obliger a bouger 
-un équipement spécial avec différent effets( une classe a choisir avant le combat, archer, chevalier, ... ).

**Comment by paly2** [comment]
> un joueurs qui ne bouge plus pendant 5 ou 10 sec prend des dégâts pour l'obliger a bouger

Super idée, je vais rapidement implémenter ça !

> un équipement spécial avec différent effets( une classe a choisir avant le combat, archer, chevalier, ... ).

C'est plus compliqué, parce que cela implique à nouveau de contrôler le stuff. On retrouve le même problème

**Comment by paly2** [comment]
@matt8r: la détection de l'immobilité est implémentée dans https://github.com/Mynetest/pvpplus/commit/f611843dbb7d2af218e79cc37c481e159b32649d. Il faut ajouter l'option `damage_motionless` à la commande `/tournament` pour l'activer.

**Comment by matt8fr** [comment]
parfait merci ! j’attends avec grande impatience la 0.4.16 pour l'autocomplétion des commandes !

**Comment by paly2** [comment]
> j’attends avec grande impatience la 0.4.16 pour l'autocomplétion des commandes !

Euh, l'autocomplétition des commandes complètera juste la commande. Elle ne pourra pas compléter, en l'occurence, les options de la commande `/tournament`

**Comment by matt8fr** [comment]
ha ? sur Minecraft l'autocomplétion fonctionne avec les option et même plus (un TAB après avoir taper: /tp complète avec les coordonné XYZ du joueur) , je m'attendait a avoirs la même chose, finalement les dev minetest copie uniquement les défaut de minecraft ? on verra bien.

**Comment by paly2** [comment]
C'est que l'API de registration des commandes de MT est assez bas niveau en ce qui concerne les paramètres. Les paramètres de la commande sont passés bruts à la fonction correspondante, qui doit se débrouiller elle-même pour les traiter, sans que Minetest ne sache comment elle s'y prend.

**Comment by matt8fr** [comment]
ok je comprend c'est plus un souci de fonctionnement technique anarchique 😄
