### ISSUE TITLE
gestion du commerce

### ISSUE THREAD

**Issue by matt8fr** [MT-Eurythmia/Eurythmia-server#91]
Je me demander si on ne devrait pas établir quelque règles pour les modérateur pour la vente d’items?
Barème pour les items rare, ...
Zone commerciale ?

**Comment by paly2** [comment]
Le barème risque d'être difficile à établir: il dépend certes de l'offre (probabilité de génération), mais aussi de la demande (ce qui ne se calcule pas mais se constate).

Je pense que le plus simple est de demander aux joueurs qui ont le privilège creative de ne pas vendre ni donner d'items, en laissant cette tâche aux joueurs qui doivent eux-même se procurer ce qu'ils utilisent et vendent (et ont ainsi une idée bien plus exacte de leur valeur, sans risque de sous-estimation). D'ailleurs, beaucoup ont commencé leur propre magasin ! À mon avis, il serait bien de lancer un appel à des joueurs sans creative pour terminer le centre commercial (légèrement au nord du spawn) abandonné depuis longtemps, et d'en faire une zone commerciale officielle gérée par ces joueurs.

**Comment by mgl512** [comment]
Pour la tour de commerce elle-même, je pense qu'elle devrait etre modifiée dans un style plus médiéval (avec un chapeau pointu et un étage qui soit un balcon dessous peut-etre) pour aller avec le chateau. 

Mettre les commerces à l'intérieur ne me tente pas trop parce que les joueurs disparaissent. Il y a déjà quelques boutiques autour du spawn dont les propriétaires ne viennent plus. On aurait plein de commerces fermés/inutilisables et des joueurs qui voudraient ouvrir des boutiques alors qu'il n'y a plus de place pour eux. En revanche, plutôt que des boutiques, mettre des téléporteurs vers des boutiques... Quand les joueurs ont disparu depuis longtemps, on casse leur téléporteur dans la tour et on le remplace par celui d'un joueur actif. 

Comme ça ils font les boutiques qu'ils veulent, grandes comme ils veulent et même aussi nombreuses qu'ils veulent. On leur met un téléporteur sur leur propre réseau "boutique" dans la tour avec un nom particulier pour celui qui se trouve dans la tour pour que les clients puissent revenir facilement au téléporteur de départ. On peut installer plein de vendeurs dans la tour, il y a peu de chances qu'il y ait un conflit d'espace. Sans y avoir trop réfléchi, ça me semble faisable sans trop de surcharge pour les modérateurs, qui gèreraient les demandes d'installation de travelnets de commerce dans la tour. Tout modo qui a accès à la tour et le priv special travelnet devrait pouvoir s'en sortir. C'est les demandes elles-memes qui posent peut-etre problème : à qui les faire et comment les diffuser aux modos capables d'y répondre ?

**Comment by matt8fr** [comment]
je suis d'accord avec le Doc le centre commercial il faut le refaire, travelnet a l'interieur qui donne sur les boutique des joueur au 4 coins de la map (demander au joueurs/vendeur de faire des bâtiments plus ou moins articuler pareille ?).

**Comment by mgl512** [comment]
J'ai sauvegardé le vieux centre commerciel ('commerce_-_SkyHal.we' je crois) et commencé à construire une tour de commerce médiévale à la place. En dehors de placer des blocs pour empêcher la lumière de passer à travers les murs, je ne m'occuperai pas du tout de l'aménagement intérieur. J'imagine un escalier en colimaçon de 3x3 surtout décoratif au milieu dont le poteau central serait remplacé par des ascenseurs aux différents étages. 

J'imagine que ce serait bien d'avoir une politique pour l'attribution des boites travelnet. Comme par exemple ne pas donner de travelnet à quelqu'un dont le magasin est trop moche. Je garde l'idée de fixer un nom particulier de réseau à la place du joueur et un nom particulier pour son travelnet dans la tour, comme réseau "boutique" et boite "tour". Peut-etre en anglais. Une politique d'espace physique serait bien aussi: que tout modo compétent pour placer un travelnet à un joueur sache où placer la prochaine boite dans la tour.

**Comment by matt8fr** [comment]
Le buzz des vending machin a l'air d’être passer, je me demande si il serait pas mieux finalement de faire des boutique directement dans la tours?
