### ISSUE TITLE
News

### ISSUE THREAD

**Issue by matt8fr** [MT-Eurythmia/Eurythmia-server#98]
un joueur a demander a ajouter ce [mod](https://github.com/Bremaweb/news) qui permet d'avoirs dans new's a l'aide de la cmd /news. apparemment les news s'ouvre également a la connexion sur le serveur (je pense que l'on peux supprimer cette fonction, non ?)
que pensez vous de ce mod ?

**Comment by paly2** [comment]
Ce mod est utilisé par MinetestForFun, et, personnellement, je n'ai jamais lu les news... Je pense que cela ajouterait de la complexité (maintenance d'un fichier news.txt, soit manuellement, soit automatiquement avec les commits sur le serveur) pour pas grand-chose (aucun joueur ne lirait les news, et si certains le souhaitent, ils peuvent déjà le faire en allant consulter les commits sur GitHub).

De plus, le formspec est trop grand pour les écrans des téléphones (et peut-être des tablettes, aussi) pour qui le bouton "Ok" est en dehors de l'écran, si bien que la plupart des joueurs Android ne pourraient pas le fermer (c'est même, sur MinetestForFun, le moyen utilisé pour ne pas avoir de joueurs utilisant des clients Android).

**Comment by mgl512** [comment]
Moi aussi j'en garde de mauvais souvenirs sur MInetestForFun. Là-bas, ça servait à donner des nouvelles du développement du serveur. Ça n'intéressait personne à part les développeurs à plein temps, qui ne jouaient pas... Et ils nous forçaient à les lire en plus, entourés de mobs surpuissants prêts à nous one-shot. 

Il aurait fallu pouvoir l'utiliser pour donner des nouvelles de ce qui se passe sur la map, des constructions en cours, des events à venir, le seul vrai intérêt d'une commande pareille. Mais le mod n'est pas fait pour ça, par nature, parce que seuls les gens qui ont accès au répertoire du monde sur le serveur peuvent alimenter les nouvelles. C'est un système qui est hostile à tout le monde sauf l'administrateur. 

Ce qui me plairait, c'est un objet livre de référence qui serait édité par l'équipe de rédaction des Echos de Woodbury et un moyen qui permette d'obtenir une copie de son contenu actuel. Un journal magique. Mais je ne sais pas faire ça!

**Comment by matt8fr** [comment]
@paly2  je comprend parfaitement au vue de tes explication que se n'est pas le mod qu'il nous faut !
@mgl512 C'est exactement ce a quoi j'ai pensé quand shurik ma parler du mod ! que quelque joueurs puissent fournir au reste de la communauté, des news, annonce ..... l'idée d'un livre est intéressant mais effectivement comment les distribuer comme il faut?

**Comment by paly2** [comment]
On peut créer un mod pour ça. Un bouton de l'inventaire permettrait aux joueurs de lire les news, et une commande permettrait aux joueurs possédant le privilège adéquat de les éditer.
Par contre je ne pourrai pas le faire tout de suite, j'ai déjà plusieurs projets en cours...

**Comment by matt8fr** [comment]
Cela serait parfait, tkt on attendra !

**Comment by matt8fr** [comment]
Je vous partage ma réflexion personnel sur se que devrait être le mod news:
j'ai au début pensé a un journal craftable pour consulter les news et/ou écrire les news dans ce même journal quand on a le privs mais je me doute que le codage ne serait pas simple, puis crafter un journal pour editer les new c'est pas top.

autre possibilité, comme tu l'a dit @paly2 un bouton dans l'inventaire pour consulter les news serait vraiment plus simple, directement éditable dans l'inventaire pour les joueurs qui on le privs, je pense aussi a une notification qui s'afficherait quelque secondes a la connexion.

**Comment by paly2** [comment]
https://github.com/Mynetest/Mynetest-server/commit/40910f8252de3951b5065b67ee58d94dfe3a50e2

Un bouton dans l'inventaire permet de voir les news. Les joueurs possédant le privilège `news_editor` ont un bouton `Submit` en plus dans leur formspec, qui leur permet d'enregistrer les news après les avoir modifié.

**Comment by matt8fr** [comment]
Je ne l'attendait pas si tôt ! je vais tester ca ! et merci

**Comment by matt8fr** [comment]
le mod est en jeux depuis 15 jours, il ne manque qu'une notif a la connexion quand les news ont était éditer,
a-par ça tous est parfait.

**Comment by mega-gigaMynetest** [comment]
Dans ce cas cela nous fait une issue de moins 😉
